= Settings
Toby Twigger <tobytwigger1@gmail.com>
:description: Using settings in a module
:keywords: settings,module settings,form schema,form,.env,environment,setting listener,config

== Types of Settings

It's generally better to reuse a module rather than creating a new one,
since it leads to less code to maintain, fewer bugs and less time
spent developing! Therefore, rather than creating for example a file
upload module, and a multiple file upload module, it'd be better if we
could create a single file upload and give the user the choice of
allowing multiple file uploads or not.

For this, we use settings. A module registers the settings it needs,
then a user fills them out when creating a module instance. You can
access the setting values in your controllers/blade templates.

To make things a bit more flexible, there are three types of settings.

- **Module settings**. These are set whenever a new instance of your module is set up, and so will be things related to a specific module instance. Think 'Page Title', 'Allowed file types' or 'Approval required'. These are the settings you will normally use when creating a module

[IMPORTANT]
====
It's important not to confuse these with permissions, which only allow specific people to do something rather than a setting for the whole module instance. 
====

- **Site Settings**. These settings are set once in the whole portal, and are only set by admins. They're normally something like the title of the site, the theme to use or whether to cache filter results. Modules mostly won't use this, although there may be cases where you'll find it useful. The main use of these, when building for the portal, is in building integrations or extensions rather than modules. The UnionCloud integration uses site settings to control its behaviour, as it's not a module so can't use module settings

- **User Settings**. Like site settings, their value applies to the whole site. These are specific to a certain user though, and are mostly used for things like dark/light mode, notification preferences or whether to use high contrast text. It' even less likely you'll use these, but they're there if you want!

Anything that you'd usually put in a configuration file either belongs as a global Site Setting or a user setting. We recommend putting a significant amount of config into the setting format, so even non-technical users can customise their site.

== Module Settings

These are the settings modules may ask the user to set each time a new module instance is made.

=== Defining Module Settings

To define settings, you should create a 'settings' method in your
service provider and return a form schema. To learn more about form
schemas, see the
https://github.com/tobytwigger/form-schema-generator[FormSchema
package].

====
[source,php]
----
public function settings(): Form
{
    return \FormSchema\Generator\Form::make()->withGroup(
        \FormSchema\Generator\Group::make('Page Settings')->withField(
            \FormSchema\Generator\Field::input('page_title')->inputType('text')->default('Title of the Page')
        )
    )->getSchema();
}
----
====

==== Custom Fields

Although the FormSchema package provides a number of fields, you may
sometimes need to make your own. For example, you may need want a third
party login button which redirects to an oauth URL, with a dropdown of
recent logins. This can be created by creating a custom component as per
the
https://vue-generators.gitbook.io/vue-generators/fields/custom_fields[VueFormGenerator
Vue Package].

Since your component will need to be used throughout the site, not just
in your module, you need to globally register the javascript file that
registers this component as a custom field. This should be in its own
file. You can add the following to your service provider boot method to
load a script on every page to be used for settings:

The `+components.js+` script should look something like

[source,javascript]
----
import CustomComponent from './components/CustomComponent';

Vue.component('field-modulealiasCustomComponent', CustomComponent);
----

Having added the script to your .mix file and compiled it, you can add
the following to your service provider to load the script globally:

[source,php]
----
public function boot()
{
    parent::boot();
    $this->registerGlobalScript('modules/module-alias/js/components.js');
}
----


=== Accessing Setting Values

The SDK handles the assignment of the settings in a module. To access a
settings value, use the settings() helper: `+settings($key, $default = null)+`.

This will return the value of the setting, or the default if the setting is not given.

=== Setting listeners

If you want to respond to settings being changed, you can hook into the
events fired when settings are created, saved, deleted etc.

==== Creating a Setting Listener

To create a settings listener, extend the `+\BristolSU\Support\ModuleInstance\Settings\SettingsListener+` class and add methods to handle different events. These events will correlate to the Eloquent events.

[source,php]
----
class NameSettingListener extends \BristolSU\Support\ModuleInstance\Settings\SettingListener
{
    protected $key = 'name'; // Key of the setting to trigger on

    public function onSaved(ModuleInstanceSetting $setting)
    {
        // Handle the setting change
    }
}
----

==== Register a Setting Listener

You should register a setting listener by including it in your `+$settingListeners+` array in the service provider.

[source,php]
----
protected $settingListeners = [
    \My\Namespace\NameSettingListener::class,
    ...
];
----

== Site Settings

These are settings that are set once for the entire instance of the portal. Each setting is defined by creating a class, containing information about the setting and its value. Settings should be grouped together with a group, then put into a category. Settings can be in more than one group or category if you want.

For example, we may have defined a ```BristolSU\Portal\Settings\SiteNameSetting``` class which has information about the site name. It's a site setting as it's set once for everyone and is used outside a module instance.

This setting is normally grouped in a 'Branding' group and a 'Setup' category. This means users will see a 'Setup' option in settings, and will then see the setting with a 'Branding' heading. However this setting would also make sense in the 'appearance' section in settings.

=== Defining Settings

To define a setting, create a class to represent the setting (for this example, we'll create a ```SiteNameSetting``` in the ```BristolSU\Portal\Setting``` namespace. To be a site setting, we extend the ```\BristolSU\Support\Settings\Definition\GlobalSetting``` abstract class.

[source,php]
----
class SiteNameSetting extends \BristolSU\Support\Settings\Definition\GlobalSetting
{

    public function rules(): array
    {
        return [
            'site_name' => 'required|string|min:2|max:20'
        ];
    }
    
    public function key(): string
    {
        return 'appearance.branding.site_name';
    }

    public function defaultValue()
    {
        return 'The Bristol SU Portal';
    }

    public function fieldOptions(): Field
    {
        return \FormSchema\Generator\Field::input($this->inputName())->inputType('text')
            ->label('Site Name')
            ->hint('This will be shown in the header of the site')->getSchema();
    }

}
----

==== Setting Details

Each key has to have a unique key. This will usually be the category, group and setting name concatenated with a full stop, but it can be anything as long as it's unique. Return this value in the ```key``` function.

The ```defaultValue``` function should return the default value. This will be shown to the user when editing the value for the first time, and will be used as the setting value if it hasn't been set yet.

==== Input field schema

The ```fieldOptions``` function should return a field schema which defines how the setting should be set. This schema will be converted into HTML and shown to the user when they're editing the setting value. See the https://github.com/tobytwigger/form-schema-generator[form schema generator] repository for more information.

The name of the component should be set as the result of ```$this->inputName()```, which will help ensure unique names.

==== Validation

To make sure any setting changes are valid, you should return a set of validation rules. The index of the rules array is ```$this->inputName()```, and you can define the rules as an array of rule objects or rule object aliases, or a string of rule object aliases with a pipe (|) character separating them. This should all be familiar as it's the same as you'd expect for a Laravel Request class.

If you need a bit more customisation, you can instead override the ```validator``` method. This accepts the new value, and should return a ```\Illuminate\Contracts\Validation\Validator``` instance.

[source,php]
----
public function validator($value): Validator
{
    return \Illuminate\Support\Facades\Validator::make([
        $this->inputName() => $value
    ], [
        $this->inputName() => 'required|string'
    ]);
}
----

=== Registering Settings

Having created a setting, you need to register it so the sdk knows it exists. This should be done in the boot method in your package or module service provider. Use the ```BristolSU\Support\Settings\Concerns\RegistersSettings``` trait to give you access to the ```registerSettings()``` method.

There are a couple of ways to register settings, so pick which one you prefer! They all make use of the ```registerSettings()``` function. Each method results in a category, group and setting being regisered together.

==== Use chained functions

This method uses the category, group and registerSetting methods. Having called ```registerSettings()``` you can call ```category()```, passing it an instance of the category to register. You can then call ```group()``` to register the group, then ```registerSetting()``` to register a setting. This final function can be called multiple times to register multiple settings.

[source,php]
----
// In the Service Provider
public function boot()
{
    $this->registerSettings()
         ->category(new MyCategory())
         ->group(new MyGroup())
         ->regiserSetting(new MySettingOne())
         ->registerSetting(new MySettingTwo());
}
----

==== Use a callback

This is very similar to the chained function method, except the chaining happens in a callback.

[source,php]
----
// In the Service Provider
public function boot()
{
    $this->registerSettings()
        ->category(new MyCategory(), function($registrar) {
            $registrar->group(new MyGroup(), function($registrar) {
                $registrar->registerSetting(new MySettingOne());
                $registrar->registerSetting(new MySettingTwo());
            });
        });
}
----

You can also mix and match the two methods.

[source,php]
----
// In the Service Provider
public function boot()
{
    $this->registerSettings()
        ->category(new MyCategory(), function($registrar) {
            $registrar
                ->group(new MyGroup())
                ->registerSetting(new MySettingOne())
                ->registerSetting(new MySettingTwo());
            });
        });
}
----

With this method, you call the category function, the group 
You can call the ```category($category, $callback)``` function to mass register

==== Register a single setting

If you just have one or two settings to register and don't want to use chained methods, you can just call the ```registerSetting``` method directly, passing it the setting, group and category.

[source,php]
----
// In the Service Provider
public function boot()
{
    $this->registerSettings()
        ->registerSetting(new MySettingOne(), new MyGroupOne(), MyCategoryOne());
    
    $this->registerSettings()
        ->registerSetting(new MySettingTwo(), new MyGroupTwo(), MyCategoryTwo());
}
----

=== Using Settings

Once settings have been registered, the portal will take care of showing a ui and letting the user update the setting values. You're very welcome to use the values though.

As with registering settings, there are lots of options of ways to retrieve the setting value. These slightly differ if the setting is a user or global setting. A user setting will often ask for a user ID of the user to retrieve the setting for. For some methods, you can leave this argument out to use the currently logged in user, but the option is always there. The differences are documented in the User Settings section.

==== Using the setting class

By far the easiest way to retrieve settings is through the ```getValue()``` static method on the setting.

Under the hood, this just calls the non-static ```value()``` method on the setting class, so you can get the value whether or not you have an instance of it or not!

[source,php]
----
echo \BristolSU\Portal\Setting\SiteNameSetting::getValue(); // The Bristol SU Portal

$setting = new \BristolSU\Portal\Setting\SiteNameSetting();
echo $setting->value(); // The Bristol SU Portal
----

You can also set the value with the corresponding set functions.

[source,php]
----
\BristolSU\Portal\Setting\SiteNameSetting::setValue('The Bristol SU Portal - New Name');

$setting = new \BristolSU\Portal\Setting\SiteNameSetting();
$setting->setSettingValue('The Bristol SU Portal - New Name');
----

// SETTING A VALUE WITH THE CLASS?
// USE THE VALIDATION

==== Using the Setting facade.

You may also use the setting facade to achieve all the same features as using the setting class directly. Simply call the needed function statically on ```BristolSU\Support\Settings\Facade\Setting```.

If you need to get the key of a setting for use with this method, call the static ```getKey()``` function on the setting, or ```key()``` non-statically.

- ```getGlobalValue(string $key)``` Get the value of a global setting.
- ```setGlobal(string $key, mixed $value)``` Set the value for a global setting.

The settings facade just resolves the ```BristolSU\Support\Settings\SettingRepository``` interface, so you can also resolve that interface by typehinting it.

==== Helper functions

The ```globalSetting($key)``` function is loaded automatically and can be used anywhere. It'll retrieve the value of the global setting with the key given.

== User Settings

Unlike global settings, which are the same for all users, user settings can be modified by individual users to customise their experience of the portal.

=== Creating a user setting

Rather than extending the ```\BristolSU\Support\Settings\Definition\GlobalSetting``` class, extend ```\BristolSU\Support\Settings\Definition\UserSetting``` to define a user setting. The interface is identical to the global settings.

=== Registering a user setting

This really is identical to registering a global setting, so see above!

User settings are interacted with much the same as global settings, however a user id is optionally accepted to any functions to retrieve the value. If not given, the setting value will belong to the currently logged in user.

==== Using the settings class

Similarly to global settings, there's a static and non-static function to retrieve the setting value. The only difference is the optional user ID value given as the first argument.

[source,php]
----
echo \BristolSU\Portal\Setting\ThemeSetting::getValue($user1->id()); // dark-mode

$setting = new \BristolSU\Portal\Setting\ThemeSetting();
echo $setting->value($user2->id()); // light-mode
----

You can also set the value with the corresponding set functions. For user settings, you can set both the setting value for the user, and the default setting value to use if a user hasn't set any settings.

[source,php]
----
\BristolSU\Portal\Setting\ThemeSettingSetting::setValue('dark-mode', $user->id()); // Passing the user id in
$setting = new \BristolSU\Portal\Setting\ThemeSettingSetting();
$setting->setSettingValue('dark-mode'); // Using the logged in user

// Or for the default value
\BristolSU\Portal\Setting\ThemeSettingSetting::setDefault('light-mode');
$setting = new \BristolSU\Portal\Setting\ThemeSettingSetting();
$setting->setSettingDefault('light-mode');
----

==== Using the Setting facade.

You may also use the setting facade to achieve all the same features as using the setting class directly. Simply call the needed function statically on ```BristolSU\Support\Settings\Facade\Setting```.

If you need to get the key of a setting for use with this method, call the static ```getKey()``` function on the setting, or ```key()``` non-statically.

- ```getUserValue(string $key, int $userId = null)``` Get the value of a user setting for the given user id, or the logged in user if no id given.
- ```setForUser(string $key, mixed $value, int $userId)``` Set a setting for the given user.
- ```setForAllUsers(string $key, mixed $value)``` Set a setting for all users. This will be the setting value unless a user customises it, so acts as a default value.

==== Helper functions

The ```userSetting($key, $userId = null)``` function is loaded automatically and can be used anywhere. It'll retrieve the value of the user setting with the key given for either the user given, or the currently logged in user.
