= Releasing
Toby Twigger <tobytwigger1@gmail.com>
:description: How to go about releasing a module
:keywords: release, finished module, publish

Once your module is ready to go, and you've written all the necessary tests, you want to open it to the world. This page will take you through the necessary steps to make sure your module can be used by others.

== Meta files in the repository

To be accepted by the portal, your repository needs to meet community standards. This means you'll need to ensure your repository has the following files:

- CHANGELOG.md - A changelog to keep track of the changes between releases of your module. This should look something like...
[source,markdown]
----
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [1.0.1] - (18/03/2020)

### Added
- Use me for new features.
### Changed
- Use me for changes in existing functionality.
### Deprecated
- Use me for soon-to-be removed features.
### Removed
- Use me for now removed features.
### Fixed
- Use me for any bug fixes.
### Security
- Use me in case of vulnerabilities.

## [1.0] - (28/02/2020)

### Added
- Initial Release

[Unreleased]: https://github.com/username/repository/compare/v1.0.1...HEAD
[1.0.1]: https://github.com/username/repository/compare/v1.0...v1.0.1
[1.0]: https://github.com/username/repository/releases/tag/v1.0
----
- CODE_OF_CONDUCT.md. Feel free to write your own, but link:{attachmentsdir}/CODE_OF_CONDUCT.md[here] is the one we use for all our projects.
- CONTRIBUTING.md. A description of how to contribute to the project. Ours can be found link:{attachmentsdir}/CONTRIBUTING.md[here].
- LICENCE.md. The licence for your project. This will nearly always be the GNU General Public License v3.0, found https://www.gnu.org/licenses/gpl-3.0.txt[here].
- README.md. A description of your module. A template can be found link:{attachmentsdir}/README.md[here].
- .gitattributes. This specifies (amongst other things) the files that aren't needed for your code to run, and helps keep your module small when installed in the portal.
[source,gitignore]
----
* text=auto
/tests export-ignore
composer.lock export-ignore
.gitignore export-ignore
.gitattributes export-ignore
package-lock.json export-ignore
phpunit.xml export-ignore
CHANGELOG.md export-ignore
CODE_OF_CONDUCT.md export-ignore
CONTRIBUTING.md export-ignore
/docs export-ignore
----

== Documentation

To make your module as easy to use as possible, we strongly recommend documenting your work. To have your documentation included on the Bristol SU Documentation site, you must use antora.

This may sound scary, but it's really simple to get started! We see documentation as being just as important as the code, and therefore should be kept in the same place. Generally this should be a `+/docs+` folder.

TIP: The template module includes the documentation framework.

=== Structure

The general structure of the `+docs+` folder should be as follows:

----
- /docs
    - antora.yml <1>
    - /modules
        - /users <2>
            - nav.adoc <3>
            - /pages
                - dummy-page.adoc <4>
            - /images
        - /admins <5>
        - /setup <6>
        - /developers <7>
----
<1> The `+antora.yml+` file describes your documentation, giving it a version and a name. An example `+antora.yml+` file can be found below.
<2> Where your user documentation lives. This should focus on how to use your module as a user
<3> The navigation file. This defines the layout of the section. Each folder has one of these files. An example is given below.
<4> An example page. Again, an example is given below.
<5> The admin documentation. This should focus on how to use the admin side of the module
<6> THe setup documentation. This should focus on what each setting does, what the permissions do, etc. It should make the setup process using your module as easy as possible.
<7> The developer documentation (optional). Contains any documentation you think may help future developers, or yourself.

=== Example Files

.Example `+antora.yml+` file
****

[source,yaml]
----
name: module-mymodule <1>
title: My Module <2>
version: v1.2.3 <3>
asciidoc:
 attributes:
  page-repo-url: https://github.com/bristol-su/support <4>
start_page: users:index.adoc <5>
nav: <6>
 - modules/users/nav.adoc
 - modules/admins/nav.adoc
 - modules/developers/nav.adoc
----
<1> The alias of your module prefixed with 'module-'. This is very important, else the module won't show up in the documentation.
<2> The title of your module
<3> The version of your module. This should be kept up to date each time you release a new version.
<4> The repository URL of your project (optional)
<5> The initial page.
<6> The list of navigations within your documentation.


****


.Example `+nav.adoc+` file
****

[source,asciidoc]
----
.Users <1>
* xref:dummy-page.adoc[Dummy Page] <2>
----
<1> The section of the documentation.
<2> A link to the page of your module. In reality, you can have as many of these as you want. See the https://docs.antora.org/antora/2.3/navigation/files-and-lists/[Antora documentation] for more information.
****



.Example `+dummy-page.adoc+` file
****

[source,asciidoc]
----
= The title of my page
Toby Twigger <tobytwigger1@gmail.com>
:description: A description of this page
:keywords: A comma separated, list of, keywords

...

----
****

== Making your module downloadable

Use packagist

== Pull requests

To portal and docs
