Bristol SU Support Package: BristolSU\Support\Connection\RegisteredConnector Class Reference
BristolSU\Support\Connection\RegisteredConnector Class Reference
Public Member Functions
getName ()
setName (string $name)
getDescription ()
setDescription (string $description)
getService ()
setService (string $service)
getAlias ()
setAlias (string $alias)
getConnector ()
setConnector (string $connector)
toArray ()
toJson ($options=0)
__toString ()
Private Attributes
$name
$description
$service
$alias
$connector
Detailed Description
A class to hold a connector and its metadata, and gracefully cast to json or array
Definition at line 12 of file RegisteredConnector.php.
Member Function Documentation
__toString()
BristolSU\Support\Connection\RegisteredConnector::__toString ()
Cast the registered connector to a string
Returns
string Representation of the registered connector as json (a string)
Definition at line 188 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\toJson().
getAlias()
BristolSU\Support\Connection\RegisteredConnector::getAlias ()
Get the alias of the connector
Returns
string Alias of the connector
Definition at line 118 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$alias.
Referenced by BristolSU\Support\Connection\ConnectorStore\registerConnector(), and BristolSU\Support\Connection\RegisteredConnector\toArray().
getConnector()
BristolSU\Support\Connection\RegisteredConnector::getConnector ()
Get the connector class name
Returns
string Class name of the connector
Definition at line 139 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$connector.
Referenced by BristolSU\Support\Connection\RegisteredConnector\toArray().
getDescription()
BristolSU\Support\Connection\RegisteredConnector::getDescription ()
Get the description of the connector
Returns
string Description of the connector
Definition at line 76 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$description.
Referenced by BristolSU\Support\Connection\RegisteredConnector\toArray().
getName()
BristolSU\Support\Connection\RegisteredConnector::getName ()
Get the name of the connector
Returns
string Name of the connector
Definition at line 55 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$name.
Referenced by BristolSU\Support\Connection\RegisteredConnector\toArray().
getService()
BristolSU\Support\Connection\RegisteredConnector::getService ()
Get the service the connector supplies
Returns
string Service the connector supplies
Definition at line 97 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$service.
Referenced by BristolSU\Support\Connection\ConnectorRepository\forService(), and BristolSU\Support\Connection\RegisteredConnector\toArray().
setAlias()
BristolSU\Support\Connection\RegisteredConnector::setAlias (string $alias)
Set the alias of the connector
Parameters
string $alias Alias of the connector
Returns
void
Definition at line 129 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$alias, and function\alias().
setConnector()
BristolSU\Support\Connection\RegisteredConnector::setConnector (string $connector)
Set the class name
Parameters
string $connector Class name of the connector
Returns
void
Definition at line 150 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$connector.
setDescription()
BristolSU\Support\Connection\RegisteredConnector::setDescription (string $description)
Set the description of the connector
Parameters
string $description Description of the connector
Returns
void
Definition at line 87 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$description.
setName()
BristolSU\Support\Connection\RegisteredConnector::setName (string $name)
Set the name of the connector
Parameters
string $name Name of the connector
Returns
void
Definition at line 66 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$name.
setService()
BristolSU\Support\Connection\RegisteredConnector::setService (string $service)
Set the service the connector supplies
Parameters
string $service Service the connector supplies
Returns
void
Definition at line 108 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\$service.
toArray()
BristolSU\Support\Connection\RegisteredConnector::toArray ()
Cast the registered connector to an array
Returns
array Representation of the registered connector as an array
Definition at line 160 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\getAlias(), BristolSU\Support\Connection\RegisteredConnector\getConnector(), BristolSU\Support\Connection\RegisteredConnector\getDescription(), BristolSU\Support\Connection\RegisteredConnector\getName(), and BristolSU\Support\Connection\RegisteredConnector\getService().
Referenced by BristolSU\Support\Connection\RegisteredConnector\toJson().
toJson()
BristolSU\Support\Connection\RegisteredConnector::toJson ($options = 0)
Cast the registered connector to json
Parameters
int $options Options for json encoding
Returns
string Representation of the registered connector as json
Definition at line 178 of file RegisteredConnector.php.
References BristolSU\Support\Connection\RegisteredConnector\toArray().
Referenced by BristolSU\Support\Connection\RegisteredConnector\__toString().
Member Data Documentation
$alias
BristolSU\Support\Connection\RegisteredConnector::$alias private
Definition at line 41 of file RegisteredConnector.php.
Referenced by BristolSU\Support\Connection\RegisteredConnector\getAlias(), and BristolSU\Support\Connection\RegisteredConnector\setAlias().
$connector
BristolSU\Support\Connection\RegisteredConnector::$connector private
Definition at line 48 of file RegisteredConnector.php.
Referenced by BristolSU\Support\Connection\RegisteredConnector\getConnector(), and BristolSU\Support\Connection\RegisteredConnector\setConnector().
$description
BristolSU\Support\Connection\RegisteredConnector::$description private
Definition at line 27 of file RegisteredConnector.php.
Referenced by BristolSU\Support\Connection\RegisteredConnector\getDescription(), and BristolSU\Support\Connection\RegisteredConnector\setDescription().
$name
BristolSU\Support\Connection\RegisteredConnector::$name private
Definition at line 20 of file RegisteredConnector.php.
Referenced by BristolSU\Support\Connection\RegisteredConnector\getName(), and BristolSU\Support\Connection\RegisteredConnector\setName().
$service
BristolSU\Support\Connection\RegisteredConnector::$service private
Definition at line 34 of file RegisteredConnector.php.
Referenced by BristolSU\Support\Connection\RegisteredConnector\getService(), and BristolSU\Support\Connection\RegisteredConnector\setService().
The documentation for this class was generated from the following file:
src/Connection/RegisteredConnector.php