Bristol SU Support Package: BristolSU\Support\Testing\TestCase Class Reference
BristolSU\Support\Testing\TestCase Class Reference
Public Member Functions
stubControl ()
setUp ()
alias ()
getEnvironmentSetUp ($app)
assertModelEquals (Model $expected, Model $actual)
createLogicTester ($true=[], $false=[], $user=null, $group=null, $role=null)
assertRequiresAuthorization ($method, $route, $ability=null, $parameters=[])
beUser ($user)
mockControl ($method, $uri, $response, $inject=false)
beGroup ($group)
beRole ($role)
adminUrl ($path='')
userUrl ($path='')
apiUrl ($path='', $admin=false)
bypassAuthorization ()
Protected Member Functions
getPackageProviders ($app)
Protected Attributes
$moduleInstance
$activity
$databaseUser
$user
$group
$role
$controlClient = null
$logicTester = null
$activityInstance
Detailed Description
Definition at line 31 of file TestCase.php.
Member Function Documentation
adminUrl()
BristolSU\Support\Testing\TestCase::adminUrl ($path = '')
Parameters
string $path
Returns
string
Definition at line 289 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\alias().
alias()
BristolSU\Support\Testing\TestCase::alias () abstract
Returns
string
Referenced by BristolSU\Support\Testing\TestCase\adminUrl(), BristolSU\Support\Testing\TestCase\assertRequiresAuthorization(), BristolSU\Support\Testing\TestCase\setUp(), and BristolSU\Support\Testing\TestCase\userUrl().
apiUrl()
BristolSU\Support\Testing\TestCase::apiUrl ($path = '', $admin = false)
Parameters
string $path
Returns
string
Definition at line 313 of file TestCase.php.
assertModelEquals()
BristolSU\Support\Testing\TestCase::assertModelEquals (Model $expected, Model $actual)
Parameters
Model $expected
Model $actual
Definition at line 163 of file TestCase.php.
assertRequiresAuthorization()
BristolSU\Support\Testing\TestCase::assertRequiresAuthorization ($method, $route, $ability = null, $parameters = [])
Parameters
$method
$route
null $ability
array $parameters
Definition at line 213 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\alias(), BristolSU\Support\Testing\TestCase\beGroup(), BristolSU\Support\Testing\TestCase\beRole(), and BristolSU\Support\Testing\TestCase\beUser().
beGroup()
BristolSU\Support\Testing\TestCase::beGroup ($group)
Parameters
$group
Returns
$this
Definition at line 267 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\$group, and BristolSU\Support\Testing\TestCase\mockControl().
Referenced by BristolSU\Support\Testing\TestCase\assertRequiresAuthorization(), and BristolSU\Support\Testing\TestCase\bypassAuthorization().
beRole()
BristolSU\Support\Testing\TestCase::beRole ($role)
Parameters
$role
Returns
$this
Definition at line 278 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\$role, and BristolSU\Support\Testing\TestCase\mockControl().
Referenced by BristolSU\Support\Testing\TestCase\assertRequiresAuthorization(), and BristolSU\Support\Testing\TestCase\bypassAuthorization().
beUser()
BristolSU\Support\Testing\TestCase::beUser ($user)
Parameters
$user
Returns
$this
Definition at line 239 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\$user, and BristolSU\Support\Testing\TestCase\mockControl().
Referenced by BristolSU\Support\Testing\TestCase\assertRequiresAuthorization(), and BristolSU\Support\Testing\TestCase\bypassAuthorization().
bypassAuthorization()
BristolSU\Support\Testing\TestCase::bypassAuthorization ()
Definition at line 321 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\beGroup(), BristolSU\Support\Testing\TestCase\beRole(), and BristolSU\Support\Testing\TestCase\beUser().
createLogicTester()
BristolSU\Support\Testing\TestCase::createLogicTester ($true = [], $false = [], $user = null, $group = null, $role = null)
Parameters
array $true
array $false
null $user
null $group
null $role
Definition at line 175 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\$group, BristolSU\Support\Testing\TestCase\$logicTester, BristolSU\Support\Testing\TestCase\$role, and BristolSU\Support\Testing\TestCase\$user.
getEnvironmentSetUp()
BristolSU\Support\Testing\TestCase::getEnvironmentSetUp ($app)
Parameters
Application $app
Definition at line 114 of file TestCase.php.
getPackageProviders()
BristolSU\Support\Testing\TestCase::getPackageProviders ($app) protected
Parameters
Application $app
Returns
array
Definition at line 337 of file TestCase.php.
mockControl()
BristolSU\Support\Testing\TestCase::mockControl ($method, $uri, $response, $inject = false)
Parameters
$method
$uri
$response
bool $inject
Definition at line 252 of file TestCase.php.
Referenced by BristolSU\Support\Testing\TestCase\beGroup(), BristolSU\Support\Testing\TestCase\beRole(), and BristolSU\Support\Testing\TestCase\beUser().
setUp()
BristolSU\Support\Testing\TestCase::setUp ()
Todo:
remove support from here
Definition at line 80 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\alias().
stubControl()
BristolSU\Support\Testing\TestCase::stubControl ()
Definition at line 74 of file TestCase.php.
userUrl()
BristolSU\Support\Testing\TestCase::userUrl ($path = '')
Parameters
string $path
Returns
string
Definition at line 301 of file TestCase.php.
References BristolSU\Support\Testing\TestCase\alias().
Member Data Documentation
$activity
BristolSU\Support\Testing\TestCase::$activity protected
Definition at line 42 of file TestCase.php.
$activityInstance
BristolSU\Support\Testing\TestCase::$activityInstance protected
Definition at line 72 of file TestCase.php.
$controlClient
BristolSU\Support\Testing\TestCase::$controlClient = null protected
Definition at line 66 of file TestCase.php.
$databaseUser
BristolSU\Support\Testing\TestCase::$databaseUser protected
Definition at line 47 of file TestCase.php.
$group
BristolSU\Support\Testing\TestCase::$group protected
Definition at line 57 of file TestCase.php.
Referenced by BristolSU\Support\Testing\TestCase\beGroup(), and BristolSU\Support\Testing\TestCase\createLogicTester().
$logicTester
BristolSU\Support\Testing\TestCase::$logicTester = null protected
Definition at line 70 of file TestCase.php.
Referenced by BristolSU\Support\Testing\TestCase\createLogicTester().
$moduleInstance
BristolSU\Support\Testing\TestCase::$moduleInstance protected
Definition at line 37 of file TestCase.php.
$role
BristolSU\Support\Testing\TestCase::$role protected
Definition at line 62 of file TestCase.php.
Referenced by BristolSU\Support\Testing\TestCase\beRole(), and BristolSU\Support\Testing\TestCase\createLogicTester().
$user
BristolSU\Support\Testing\TestCase::$user protected
Definition at line 52 of file TestCase.php.
Referenced by BristolSU\Support\Testing\TestCase\beUser(), and BristolSU\Support\Testing\TestCase\createLogicTester().
The documentation for this class was generated from the following file:
src/Testing/TestCase.php