Bristol SU Support Package: BristolSU\Support\Authorization\Exception\ActivityDisabled Class Reference
BristolSU\Support\Authorization\Exception\ActivityDisabled Class Reference
Public Member Functions
setActivity (Activity $activity)
activity ()
Static Public Member Functions
static fromActivity (Activity $activity)
Protected Attributes
$activity
Detailed Description
Definition at line 7 of file ActivityDisabled.php.
Member Function Documentation
activity()
BristolSU\Support\Authorization\Exception\ActivityDisabled::activity ()
Set the activity that caused the exception to be thrown
Returns
Activity
Definition at line 43 of file ActivityDisabled.php.
References BristolSU\Support\Authorization\Exception\ActivityDisabled\$activity.
Referenced by BristolSU\Support\Authorization\Exception\ActivityDisabled\setActivity().
fromActivity()
static BristolSU\Support\Authorization\Exception\ActivityDisabled::fromActivity (Activity $activity) static
Create an instance of the exception
Parameters
Activity $activity
Returns
ActivityDisabled
Definition at line 22 of file ActivityDisabled.php.
Referenced by BristolSU\Support\Authorization\Middleware\CheckActivityEnabled\handle().
setActivity()
BristolSU\Support\Authorization\Exception\ActivityDisabled::setActivity (Activity $activity)
Set the activity that caused the exception to be thrown
Parameters
Activity $activity
Definition at line 33 of file ActivityDisabled.php.
References BristolSU\Support\Authorization\Exception\ActivityDisabled\$activity, and BristolSU\Support\Authorization\Exception\ActivityDisabled\activity().
Member Data Documentation
$activity
BristolSU\Support\Authorization\Exception\ActivityDisabled::$activity protected
Definition at line 14 of file ActivityDisabled.php.
Referenced by BristolSU\Support\Authorization\Exception\ActivityDisabled\activity(), and BristolSU\Support\Authorization\Exception\ActivityDisabled\setActivity().
The documentation for this class was generated from the following file:
src/Authorization/Exception/ActivityDisabled.php