Bristol SU Support Package: BristolSU\Support\Testing\HandlesAuthentication Class Reference
BristolSU\Support\Testing\HandlesAuthentication Class Reference
Public Member Functions
newUser ($attributes=[])
newGroup ($attributes=[])
newRole ($attributes=[])
beGroup (Group $group)
beRole (Role $role)
beUser (User $user)
Detailed Description
Trait for aiding interactions with the user/group/role system
Definition at line 13 of file HandlesAuthentication.php.
Member Function Documentation
beGroup()
BristolSU\Support\Testing\HandlesAuthentication::beGroup (Group $group)
Set a group
Parameters
Group $group
Returns
void
Exceptions
Definition at line 56 of file HandlesAuthentication.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\setUpAuthentication().
beRole()
BristolSU\Support\Testing\HandlesAuthentication::beRole (Role $role)
Set a role
Parameters
Role $role
Returns
void
Exceptions
Definition at line 69 of file HandlesAuthentication.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\setUpAuthentication().
beUser()
BristolSU\Support\Testing\HandlesAuthentication::beUser (User $user)
Set a user
Parameters
User $user
Returns
void
Exceptions
Definition at line 83 of file HandlesAuthentication.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\setUpAuthentication().
newGroup()
BristolSU\Support\Testing\HandlesAuthentication::newGroup ($attributes = [])
Create a new control group
Parameters
array $attributes Attributes to use for the group
Returns
Group
Definition at line 33 of file HandlesAuthentication.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\setUpAuthentication().
newRole()
BristolSU\Support\Testing\HandlesAuthentication::newRole ($attributes = [])
Create a new control role
Parameters
array $attributes Attributes to use for the role
Returns
Role
Definition at line 44 of file HandlesAuthentication.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\setUpAuthentication().
newUser()
BristolSU\Support\Testing\HandlesAuthentication::newUser ($attributes = [])
Create a new control user
Parameters
array $attributes Attributes to use for the user
Returns
User
Definition at line 22 of file HandlesAuthentication.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\setUpAuthentication().
The documentation for this class was generated from the following file:
src/Testing/HandlesAuthentication.php