Bristol SU Support Package: BristolSU\Support\Logic\Contracts\Audience\LogicAudience Class Reference
BristolSU\Support\Logic\Contracts\Audience\LogicAudience Class Reference
Public Member Functions
audience (Logic $logic)
userAudience (Logic $logic)
groupAudience (Logic $logic)
roleAudience (Logic $logic)
Detailed Description
Gets the audience for a logic group
Definition at line 14 of file LogicAudience.php.
Member Function Documentation
audience()
BristolSU\Support\Logic\Contracts\Audience\LogicAudience::audience (Logic $logic) abstract
Gets the audience of a logic group
Parameters
Logic $logic Logic group to get the audience from
Returns
mixed
Referenced by BristolSU\Support\Logic\Contracts\Audience\LogicAudience\groupAudience(), BristolSU\Support\Logic\Contracts\Audience\LogicAudience\roleAudience(), and BristolSU\Support\Logic\Contracts\Audience\LogicAudience\userAudience().
groupAudience()
BristolSU\Support\Logic\Contracts\Audience\LogicAudience::groupAudience (Logic $logic)
Return all groups in the logic group
Parameters
Logic $logic Logic group to test
Returns
All groups who can access the logic group
Definition at line 50 of file LogicAudience.php.
References BristolSU\Support\Logic\Contracts\Audience\LogicAudience\audience(), BristolSU\Support\Logic\Audience\AudienceMember\groups(), and BristolSU\Support\Logic\Audience\AudienceMember\roles().
roleAudience()
BristolSU\Support\Logic\Contracts\Audience\LogicAudience::roleAudience (Logic $logic)
Returns all roles in the logic group
Parameters
Logic $logic Logic group to test
Returns
All roles who can access the logic group
Definition at line 69 of file LogicAudience.php.
References BristolSU\Support\Logic\Contracts\Audience\LogicAudience\audience(), and BristolSU\Support\Logic\Audience\AudienceMember\roles().
userAudience()
BristolSU\Support\Logic\Contracts\Audience\LogicAudience::userAudience (Logic $logic)
Get the users belonging to a logic group
Extracts the user models from audiences and returns all users who can access the logic group
Parameters
Logic $logic Logic group to test
Returns
All users who can access the logic group
Definition at line 33 of file LogicAudience.php.
References BristolSU\Support\Logic\Contracts\Audience\LogicAudience\audience(), BristolSU\Support\Logic\Audience\AudienceMember\hasAudience(), and BristolSU\Support\Logic\Audience\AudienceMember\user().
The documentation for this class was generated from the following file:
src/Logic/Contracts/Audience/LogicAudience.php