Bristol SU Support Package: BristolSU\Support\Action\ActionInstanceRepository Class Reference
BristolSU\Support\Action\ActionInstanceRepository Class Reference
Public Member Functions
forEvent (int $moduleInstanceId, string $event)
forModuleInstance (int $moduleInstanceId)
getById (int $id)
all ()
update (int $id, array $attributes)
delete (int $id)
Detailed Description
Definition at line 9 of file ActionInstanceRepository.php.
Member Function Documentation
all()
BristolSU\Support\Action\ActionInstanceRepository::all ()
Get all action instances registered
Returns
Collection
Implements BristolSU\Support\Action\Contracts\ActionInstanceRepository.
Definition at line 50 of file ActionInstanceRepository.php.
delete()
BristolSU\Support\Action\ActionInstanceRepository::delete (int $id)
Delete an action instance
Parameters
int $id
Returns
void
Exceptions
ModelNotFoundException
Implements BristolSU\Support\Action\Contracts\ActionInstanceRepository.
Definition at line 81 of file ActionInstanceRepository.php.
References BristolSU\Support\Action\ActionInstanceRepository\getById().
forEvent()
BristolSU\Support\Action\ActionInstanceRepository::forEvent (int $moduleInstanceId, string $event)
Implements BristolSU\Support\Action\Contracts\ActionInstanceRepository.
Definition at line 15 of file ActionInstanceRepository.php.
forModuleInstance()
BristolSU\Support\Action\ActionInstanceRepository::forModuleInstance (int $moduleInstanceId)
Get all action instances for a given module instance
Parameters
int $moduleInstanceId ID of the module instance to get the action instances from
Returns
Collection
Implements BristolSU\Support\Action\Contracts\ActionInstanceRepository.
Definition at line 28 of file ActionInstanceRepository.php.
getById()
BristolSU\Support\Action\ActionInstanceRepository::getById (int $id)
Get an action instance by ID
Parameters
int $id
Returns
ActionInstance
Exceptions
ModelNotFoundException
Implements BristolSU\Support\Action\Contracts\ActionInstanceRepository.
Definition at line 41 of file ActionInstanceRepository.php.
Referenced by BristolSU\Support\Action\ActionInstanceRepository\delete(), and BristolSU\Support\Action\ActionInstanceRepository\update().
update()
BristolSU\Support\Action\ActionInstanceRepository::update (int $id, array $attributes)
Update an action instance
Parameters
int $id
array $attributes
Returns
ActionInstance
Exceptions
ModelNotFoundException
Implements BristolSU\Support\Action\Contracts\ActionInstanceRepository.
Definition at line 64 of file ActionInstanceRepository.php.
References BristolSU\Support\Action\ActionInstanceRepository\getById().
The documentation for this class was generated from the following file:
src/Action/ActionInstanceRepository.php