Bristol SU Support Package: BristolSU\Support\Logic\Logic Class Reference
BristolSU\Support\Logic\Logic Class Reference
Public Member Functions
filters ()
allTrueFilters ()
allFalseFilters ()
anyTrueFilters ()
anyFalseFilters ()
Protected Attributes
$fillable
$appends
Detailed Description
Represents a logic group in the database
Definition at line 12 of file Logic.php.
Member Function Documentation
allFalseFilters()
BristolSU\Support\Logic\Logic::allFalseFilters ()
Filter relationship for filters that must all be false
Returns
Definition at line 66 of file Logic.php.
Referenced by BristolSU\Support\Logic\LogicTester\evaluate().
allTrueFilters()
BristolSU\Support\Logic\Logic::allTrueFilters ()
Filter relationship for filters that must all be true
Returns
Definition at line 56 of file Logic.php.
Referenced by BristolSU\Support\Logic\LogicTester\evaluate().
anyFalseFilters()
BristolSU\Support\Logic\Logic::anyFalseFilters ()
Filter relationship for filters of which any must be false
Returns
Definition at line 86 of file Logic.php.
Referenced by BristolSU\Support\Logic\LogicTester\evaluate().
anyTrueFilters()
BristolSU\Support\Logic\Logic::anyTrueFilters ()
Filter relationship for filters of which any must be true
Returns
Definition at line 76 of file Logic.php.
Referenced by BristolSU\Support\Logic\LogicTester\evaluate().
filters()
BristolSU\Support\Logic\Logic::filters ()
Filter relationship
Returns all filters constituting the logic group
Returns
Definition at line 45 of file Logic.php.
Member Data Documentation
$appends
BristolSU\Support\Logic\Logic::$appends protected
Initial value:
= [
        'lowest_resource'
    ]
Definition at line 34 of file Logic.php.
$fillable
BristolSU\Support\Logic\Logic::$fillable protected
Initial value:
= [
        'name',
        'description',
    ]
Definition at line 19 of file Logic.php.
The documentation for this class was generated from the following file:
src/Logic/Logic.php