Bristol SU Support Package: BristolSU\Support\Filters\Filters\Group\GroupNameIs Class Reference
BristolSU\Support\Filters\Filters\Group\GroupNameIs Class Reference
Public Member Functions
options ()
evaluate ($settings)
name ()
description ()
alias ()
Public Member Functions inherited from BristolSU\Support\Filters\Contracts\Filters\GroupFilter
setModel ($model)
hasModel ()
model ()
group ()
Public Member Functions inherited from BristolSU\Support\Filters\Contracts\Filters\Filter
model ()
options ()
hasModel ()
setModel ($model)
evaluate ($settings)
name ()
description ()
alias ()
toArray ()
Detailed Description
Test the group name matches
Definition at line 10 of file GroupNameIs.php.
Member Function Documentation
alias()
BristolSU\Support\Filters\Filters\Group\GroupNameIs::alias ()
Filter alias
Returns
string Alias
Definition at line 63 of file GroupNameIs.php.
description()
BristolSU\Support\Filters\Filters\Group\GroupNameIs::description ()
Filter description
Returns
string Description
Definition at line 53 of file GroupNameIs.php.
evaluate()
BristolSU\Support\Filters\Filters\Group\GroupNameIs::evaluate ($settings)
Test if the group has the given name
Parameters
string $settings [ 'Group Name' => 'name' ]
Returns
bool
Definition at line 33 of file GroupNameIs.php.
References BristolSU\Support\Filters\Contracts\Filters\GroupFilter\group(), and BristolSU\Support\Filters\Filters\Group\GroupNameIs\name().
name()
BristolSU\Support\Filters\Filters\Group\GroupNameIs::name ()
Get the filter name
Returns
string Name
Definition at line 43 of file GroupNameIs.php.
Referenced by BristolSU\Support\Filters\Filters\Group\GroupNameIs\evaluate().
options()
BristolSU\Support\Filters\Filters\Group\GroupNameIs::options ()
Get possible options as an array
Returns
array
Definition at line 19 of file GroupNameIs.php.
The documentation for this class was generated from the following file:
src/Filters/Filters/Group/GroupNameIs.php