Bristol SU Support Package: BristolSU\Support\Module\ModuleServiceProvider Class Reference
BristolSU\Support\Module\ModuleServiceProvider Class Reference
Public Member Functions
boot ()
registerSettingListeners ()
registerScheduledCommands ()
registerRoutes ()
registerModule ()
registerPermissions ()
registerEvents ()
registerTranslations ()
registerViews ()
registerFactories ()
loadMigrations ()
mapParticipantRoutes ()
mapAdminRoutes ()
mapParticipantApiRoutes ()
mapAdminApiRoutes ()
registerCommands ()
registerAssets ()
Protected Member Functions
registerConfig ()
Protected Attributes
$defer = false
$permissions
$events = []
$commands = []
$settingListeners = []
$scheduledCommands = []
Detailed Description
Module Service Provider.
Extend this service provider to register a module
Definition at line 25 of file ModuleServiceProvider.php.
Member Function Documentation
boot()
BristolSU\Support\Module\ModuleServiceProvider::boot ()
Boot
Register translations
Register configuration
Register the module
Register module permissions
Register module events
Register views
Register factories
Register migrations to use
Register commands
Register assets
Register routes
Register settings
Register setting listeners
Register scheduled commands
Exceptions
BindingResolutionException
Definition at line 138 of file ModuleServiceProvider.php.
References BristolSU\Support\Module\ModuleServiceProvider\loadMigrations(), BristolSU\Support\Module\ModuleServiceProvider\registerAssets(), BristolSU\Support\Module\ModuleServiceProvider\registerCommands(), BristolSU\Support\Module\ModuleServiceProvider\registerConfig(), BristolSU\Support\Module\ModuleServiceProvider\registerEvents(), BristolSU\Support\Module\ModuleServiceProvider\registerFactories(), BristolSU\Support\Module\ModuleServiceProvider\registerModule(), BristolSU\Support\Module\ModuleServiceProvider\registerPermissions(), BristolSU\Support\Module\ModuleServiceProvider\registerRoutes(), BristolSU\Support\Module\ModuleServiceProvider\registerScheduledCommands(), BristolSU\Support\Module\ModuleServiceProvider\registerSettingListeners(), function\registerSettings(), BristolSU\Support\Module\ModuleServiceProvider\registerTranslations(), and BristolSU\Support\Module\ModuleServiceProvider\registerViews().
loadMigrations()
BristolSU\Support\Module\ModuleServiceProvider::loadMigrations ()
Load migrations to be used
Definition at line 286 of file ModuleServiceProvider.php.
References function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
mapAdminApiRoutes()
BristolSU\Support\Module\ModuleServiceProvider::mapAdminApiRoutes ()
Load admin API routes
Definition at line 327 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\registerRoutes().
mapAdminRoutes()
BristolSU\Support\Module\ModuleServiceProvider::mapAdminRoutes ()
Load admin routes
Definition at line 305 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\registerRoutes().
mapParticipantApiRoutes()
BristolSU\Support\Module\ModuleServiceProvider::mapParticipantApiRoutes ()
Load participant API routes
Definition at line 316 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\registerRoutes().
mapParticipantRoutes()
BristolSU\Support\Module\ModuleServiceProvider::mapParticipantRoutes ()
Load participant routes
Definition at line 294 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\registerRoutes().
registerAssets()
BristolSU\Support\Module\ModuleServiceProvider::registerAssets ()
Register assets
Definition at line 348 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerCommands()
BristolSU\Support\Module\ModuleServiceProvider::registerCommands ()
Register commmands to make available
Definition at line 338 of file ModuleServiceProvider.php.
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerConfig()
BristolSU\Support\Module\ModuleServiceProvider::registerConfig () protected
Register config
Definition at line 250 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerEvents()
BristolSU\Support\Module\ModuleServiceProvider::registerEvents ()
Register events the module fires
Exceptions
BindingResolutionException
Definition at line 228 of file ModuleServiceProvider.php.
References function\alias().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerFactories()
BristolSU\Support\Module\ModuleServiceProvider::registerFactories ()
Register factories in a non-production environment
Exceptions
BindingResolutionException
Definition at line 276 of file ModuleServiceProvider.php.
References function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerModule()
BristolSU\Support\Module\ModuleServiceProvider::registerModule ()
Register the module
Exceptions
BindingResolutionException
Definition at line 200 of file ModuleServiceProvider.php.
References function\alias().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerPermissions()
BristolSU\Support\Module\ModuleServiceProvider::registerPermissions ()
Register permissions the module uses
Exceptions
Exception
Definition at line 210 of file ModuleServiceProvider.php.
References function\alias().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerRoutes()
BristolSU\Support\Module\ModuleServiceProvider::registerRoutes ()
Register routes for the module
Definition at line 186 of file ModuleServiceProvider.php.
References BristolSU\Support\Module\ModuleServiceProvider\mapAdminApiRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapAdminRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapParticipantApiRoutes(), and BristolSU\Support\Module\ModuleServiceProvider\mapParticipantRoutes().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerScheduledCommands()
BristolSU\Support\Module\ModuleServiceProvider::registerScheduledCommands ()
Register scheduled commands
Register commands to run at scheduled times.
Exceptions
BindingResolutionException
Definition at line 175 of file ModuleServiceProvider.php.
References function\alias().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerSettingListeners()
BristolSU\Support\Module\ModuleServiceProvider::registerSettingListeners ()
Register setting listeners
Register listeners to be fired when settings are changed.
Definition at line 161 of file ModuleServiceProvider.php.
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerTranslations()
BristolSU\Support\Module\ModuleServiceProvider::registerTranslations ()
Register translations
Definition at line 242 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
registerViews()
BristolSU\Support\Module\ModuleServiceProvider::registerViews ()
Register views
Definition at line 262 of file ModuleServiceProvider.php.
References function\alias(), and function\baseDirectory().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
Member Data Documentation
$commands
BristolSU\Support\Module\ModuleServiceProvider::$commands = [] protected
Definition at line 86 of file ModuleServiceProvider.php.
$defer
BristolSU\Support\Module\ModuleServiceProvider::$defer = false protected
Definition at line 33 of file ModuleServiceProvider.php.
$events
BristolSU\Support\Module\ModuleServiceProvider::$events = [] protected
Definition at line 72 of file ModuleServiceProvider.php.
$permissions
BristolSU\Support\Module\ModuleServiceProvider::$permissions protected
Initial value:
= [
    ]
Definition at line 56 of file ModuleServiceProvider.php.
$scheduledCommands
BristolSU\Support\Module\ModuleServiceProvider::$scheduledCommands = [] protected
Definition at line 116 of file ModuleServiceProvider.php.
$settingListeners
BristolSU\Support\Module\ModuleServiceProvider::$settingListeners = [] protected
Definition at line 99 of file ModuleServiceProvider.php.
The documentation for this class was generated from the following file:
src/Module/ModuleServiceProvider.php