Bristol SU Support Package: BristolSU\Support\Module\Module Class Reference
BristolSU\Support\Module\Module Class Reference
Public Member Functions
__toString ()
toJson ($options=0)
toArray ()
getAlias ()
setAlias (string $alias)
getName ()
setName (string $name)
getDescription ()
setDescription (string $description)
getPermissions ()
setPermissions (array $permissions)
getSettings ()
setSettings (array $settings)
getTriggers ()
setTriggers (array $triggers)
setCompletionConditions (array $completionConditions)
getCompletionConditions ()
setServices (array $services)
getServices ()
Protected Attributes
$alias
$name
$description
$permissions
$settings
$triggers
$services
$completionConditions
Detailed Description
Definition at line 11 of file Module.php.
Member Function Documentation
__toString()
BristolSU\Support\Module\Module::__toString ()
Returns
false|string
Definition at line 49 of file Module.php.
References BristolSU\Support\Module\Module\toJson().
getAlias()
BristolSU\Support\Module\Module::getAlias ()
Returns
string
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 83 of file Module.php.
getCompletionConditions()
BristolSU\Support\Module\Module::getCompletionConditions ()
Returns
string
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 187 of file Module.php.
getDescription()
BristolSU\Support\Module\Module::getDescription ()
Returns
string
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 115 of file Module.php.
getName()
BristolSU\Support\Module\Module::getName ()
Returns
string
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 99 of file Module.php.
getPermissions()
BristolSU\Support\Module\Module::getPermissions ()
Returns
array
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 131 of file Module.php.
getServices()
BristolSU\Support\Module\Module::getServices ()
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 203 of file Module.php.
getSettings()
BristolSU\Support\Module\Module::getSettings ()
Returns
array
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 147 of file Module.php.
getTriggers()
BristolSU\Support\Module\Module::getTriggers ()
Returns
array
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 163 of file Module.php.
setAlias()
BristolSU\Support\Module\Module::setAlias (string $alias)
Parameters
string $alias
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 91 of file Module.php.
References function\alias().
setCompletionConditions()
BristolSU\Support\Module\Module::setCompletionConditions (array $completionConditions)
Parameters
string $completionConditions
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 179 of file Module.php.
setDescription()
BristolSU\Support\Module\Module::setDescription (string $description)
Parameters
string $description
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 123 of file Module.php.
setName()
BristolSU\Support\Module\Module::setName (string $name)
Parameters
string $name
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 107 of file Module.php.
setPermissions()
BristolSU\Support\Module\Module::setPermissions (array $permissions)
Parameters
array $permissions
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 139 of file Module.php.
setServices()
BristolSU\Support\Module\Module::setServices (array $services)
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 195 of file Module.php.
setSettings()
BristolSU\Support\Module\Module::setSettings (array $settings)
Parameters
array $settings
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 155 of file Module.php.
References function\settings().
setTriggers()
BristolSU\Support\Module\Module::setTriggers (array $triggers)
Parameters
array $triggers
Implements BristolSU\Support\Module\Contracts\Module.
Definition at line 171 of file Module.php.
toArray()
BristolSU\Support\Module\Module::toArray ()
Returns
array
Definition at line 66 of file Module.php.
References BristolSU\Support\Module\Contracts\Module\getAlias(), BristolSU\Support\Module\Contracts\Module\getCompletionConditions(), BristolSU\Support\Module\Contracts\Module\getDescription(), BristolSU\Support\Module\Contracts\Module\getName(), BristolSU\Support\Module\Contracts\Module\getPermissions(), BristolSU\Support\Module\Contracts\Module\getServices(), BristolSU\Support\Module\Contracts\Module\getSettings(), and BristolSU\Support\Module\Contracts\Module\getTriggers().
Referenced by BristolSU\Support\Module\Module\toJson().
toJson()
BristolSU\Support\Module\Module::toJson ($options = 0)
Parameters
int $options
Returns
false|string
Definition at line 58 of file Module.php.
References BristolSU\Support\Module\Module\toArray().
Referenced by BristolSU\Support\Module\Module\__toString().
Member Data Documentation
$alias
BristolSU\Support\Module\Module::$alias protected
Definition at line 17 of file Module.php.
$completionConditions
BristolSU\Support\Module\Module::$completionConditions protected
Definition at line 44 of file Module.php.
$description
BristolSU\Support\Module\Module::$description protected
Definition at line 25 of file Module.php.
$name
BristolSU\Support\Module\Module::$name protected
Definition at line 21 of file Module.php.
$permissions
BristolSU\Support\Module\Module::$permissions protected
Definition at line 29 of file Module.php.
$services
BristolSU\Support\Module\Module::$services protected
Definition at line 39 of file Module.php.
$settings
BristolSU\Support\Module\Module::$settings protected
Definition at line 33 of file Module.php.
$triggers
BristolSU\Support\Module\Module::$triggers protected
Definition at line 37 of file Module.php.
The documentation for this class was generated from the following file:
src/Module/Module.php