Bristol SU Support Package: BristolSU\Support\Testing\CreatesModuleEnvironment Class Reference
BristolSU\Support\Testing\CreatesModuleEnvironment Class Reference
Public Member Functions
createModuleEnvironment (string $alias)
setActivity (Activity $activity)
setModuleInstance (\BristolSU\Support\ModuleInstance\Contracts\ModuleInstance $moduleInstance)
setModuleIsFor (string $for)
setActivityInstance (ActivityInstance $activityInstance)
setControlUser (\BristolSU\ControlDB\Contracts\Models\User $user)
setControlGroup (\BristolSU\ControlDB\Contracts\Models\Group $group)
setControlRole (\BristolSU\ControlDB\Contracts\Models\Role $role)
setDatabaseUser (DatabaseUser $databaseUser)
getActivity ()
getModuleIsFor ()
getModuleInstance ()
getActivityInstance ()
getControlUser ()
getControlGroup ()
getControlRole ()
getDatabaseUser ()
adminUrl ($path='')
userUrl ($path='')
adminApiUrl ($path='')
userApiUrl ($path='')
Public Member Functions inherited from BristolSU\Support\Testing\HandlesAuthentication
newUser ($attributes=[])
newGroup ($attributes=[])
newRole ($attributes=[])
beGroup (Group $group)
beRole (Role $role)
beUser (User $user)
Private Member Functions
setUpModule ()
setUpAuthentication ()
setUpDatabaseUser ()
Private Attributes
$alias
$activity
$moduleInstance
$activityInstance
$for
$controlUser
$controlGroup
$controlRole
$databaseUser
Detailed Description
Trait to help set up a module testing environment
Definition at line 18 of file CreatesModuleEnvironment.php.
Member Function Documentation
adminApiUrl()
BristolSU\Support\Testing\CreatesModuleEnvironment::adminApiUrl ($path = '')
Get the url of the admin api
Parameters
string $path Url to return relative to the admin api route
Returns
string Url
Definition at line 368 of file CreatesModuleEnvironment.php.
References function\alias().
adminUrl()
BristolSU\Support\Testing\CreatesModuleEnvironment::adminUrl ($path = '')
Get the url of the admin side of a module
Parameters
string $path Url to return relative to the admin side of the module
Returns
string Url
Definition at line 340 of file CreatesModuleEnvironment.php.
References function\alias().
createModuleEnvironment()
BristolSU\Support\Testing\CreatesModuleEnvironment::createModuleEnvironment (string $alias)
Set up the module in the set configuration
Parameters
string $alias Alias of the module to set up
Exceptions
Definition at line 91 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$alias, function\alias(), BristolSU\Support\Testing\CreatesModuleEnvironment\setUpAuthentication(), BristolSU\Support\Testing\CreatesModuleEnvironment\setUpDatabaseUser(), and BristolSU\Support\Testing\CreatesModuleEnvironment\setUpModule().
getActivity()
BristolSU\Support\Testing\CreatesModuleEnvironment::getActivity ()
Get the activity to stage the module in
Returns
Activity
Definition at line 184 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$activity.
getActivityInstance()
BristolSU\Support\Testing\CreatesModuleEnvironment::getActivityInstance ()
Get the activity instance to use
Returns
ActivityInstance
Definition at line 214 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$activityInstance.
getControlGroup()
BristolSU\Support\Testing\CreatesModuleEnvironment::getControlGroup ()
Get the control group to use
Returns
Definition at line 234 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$controlGroup.
getControlRole()
BristolSU\Support\Testing\CreatesModuleEnvironment::getControlRole ()
Get the control role to use
Returns
Definition at line 244 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$controlRole.
getControlUser()
BristolSU\Support\Testing\CreatesModuleEnvironment::getControlUser ()
Get the control user to use
Returns
Definition at line 224 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$controlUser.
getDatabaseUser()
BristolSU\Support\Testing\CreatesModuleEnvironment::getDatabaseUser ()
Get the database user
Returns
DatabaseUser
Definition at line 254 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$databaseUser.
getModuleInstance()
BristolSU\Support\Testing\CreatesModuleEnvironment::getModuleInstance ()
Get the module instance to stage the module in
Returns
Definition at line 204 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$moduleInstance.
getModuleIsFor()
BristolSU\Support\Testing\CreatesModuleEnvironment::getModuleIsFor ()
Get who the module is for. One of user, group or role.
Returns
string
Definition at line 194 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$for.
setActivity()
BristolSU\Support\Testing\CreatesModuleEnvironment::setActivity (Activity $activity)
Set the activity to stage the module in
Parameters
Activity $activity
Definition at line 104 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$activity.
setActivityInstance()
BristolSU\Support\Testing\CreatesModuleEnvironment::setActivityInstance (ActivityInstance $activityInstance)
Set the activity instance to use
Parameters
ActivityInstance $activityInstance
Definition at line 134 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$activityInstance.
setControlGroup()
BristolSU\Support\Testing\CreatesModuleEnvironment::setControlGroup (\BristolSU\ControlDB\Contracts\Models\Group $group)
Set the control group to use
Parameters
\BristolSU\ControlDB\Contracts\Models\Group $group
Definition at line 154 of file CreatesModuleEnvironment.php.
setControlRole()
BristolSU\Support\Testing\CreatesModuleEnvironment::setControlRole (\BristolSU\ControlDB\Contracts\Models\Role $role)
Set the control role to use
Parameters
\BristolSU\ControlDB\Contracts\Models\Role $role
Definition at line 164 of file CreatesModuleEnvironment.php.
setControlUser()
BristolSU\Support\Testing\CreatesModuleEnvironment::setControlUser (\BristolSU\ControlDB\Contracts\Models\User $user)
Set the control user to use
Parameters
\BristolSU\ControlDB\Contracts\Models\User $user
Definition at line 144 of file CreatesModuleEnvironment.php.
setDatabaseUser()
BristolSU\Support\Testing\CreatesModuleEnvironment::setDatabaseUser (DatabaseUser $databaseUser)
Set the database user
Parameters
DatabaseUser $databaseUser
Definition at line 174 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$databaseUser.
setModuleInstance()
BristolSU\Support\Testing\CreatesModuleEnvironment::setModuleInstance (\BristolSU\Support\ModuleInstance\Contracts\ModuleInstance $moduleInstance)
Set the module instance to stage the module in
Parameters
\BristolSU\Support\ModuleInstance\Contracts\ModuleInstance $moduleInstance
Definition at line 114 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$moduleInstance.
setModuleIsFor()
BristolSU\Support\Testing\CreatesModuleEnvironment::setModuleIsFor (string $for)
Set who the module is for. Must be one of user, group or role.
Parameters
string $for
Definition at line 124 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\CreatesModuleEnvironment\$for.
setUpAuthentication()
BristolSU\Support\Testing\CreatesModuleEnvironment::setUpAuthentication () private
Set up the control authentication
Sets the user/group/role that is able to use the module for a given 'for' value.
if 'for' is 'role', will create and log in a user, group and role
if 'for' is 'group', will create and log in a user and group
if 'for' is 'user', will create and log in a user
Exceptions
Definition at line 306 of file CreatesModuleEnvironment.php.
References BristolSU\Support\Testing\HandlesAuthentication\beGroup(), BristolSU\Support\Testing\HandlesAuthentication\beRole(), BristolSU\Support\Testing\HandlesAuthentication\beUser(), BristolSU\Support\Testing\HandlesAuthentication\newGroup(), BristolSU\Support\Testing\HandlesAuthentication\newRole(), and BristolSU\Support\Testing\HandlesAuthentication\newUser().
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\createModuleEnvironment().
setUpDatabaseUser()
BristolSU\Support\Testing\CreatesModuleEnvironment::setUpDatabaseUser () private
Create a database user
Definition at line 326 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\createModuleEnvironment().
setUpModule()
BristolSU\Support\Testing\CreatesModuleEnvironment::setUpModule () private
Set up the module
Get/create the activity and bind it
Get/create a module instance and bind
Get/create an activity instance and bind
Definition at line 266 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\createModuleEnvironment().
userApiUrl()
BristolSU\Support\Testing\CreatesModuleEnvironment::userApiUrl ($path = '')
Get the url of the user api
Parameters
string $path Url to return relative to the user api route
Returns
string Url
Definition at line 382 of file CreatesModuleEnvironment.php.
References function\alias().
userUrl()
BristolSU\Support\Testing\CreatesModuleEnvironment::userUrl ($path = '')
Get the url of the user side of a module
Parameters
string $path Url to return relative to the user side of the module
Returns
string Url
Definition at line 354 of file CreatesModuleEnvironment.php.
References function\alias().
Member Data Documentation
$activity
BristolSU\Support\Testing\CreatesModuleEnvironment::$activity private
Definition at line 33 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getActivity(), and BristolSU\Support\Testing\CreatesModuleEnvironment\setActivity().
$activityInstance
BristolSU\Support\Testing\CreatesModuleEnvironment::$activityInstance private
Definition at line 46 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getActivityInstance(), and BristolSU\Support\Testing\CreatesModuleEnvironment\setActivityInstance().
$alias
BristolSU\Support\Testing\CreatesModuleEnvironment::$alias private
Definition at line 26 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\createModuleEnvironment().
$controlGroup
BristolSU\Support\Testing\CreatesModuleEnvironment::$controlGroup private
Definition at line 69 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getControlGroup().
$controlRole
BristolSU\Support\Testing\CreatesModuleEnvironment::$controlRole private
Definition at line 76 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getControlRole().
$controlUser
BristolSU\Support\Testing\CreatesModuleEnvironment::$controlUser private
Definition at line 62 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getControlUser().
$databaseUser
BristolSU\Support\Testing\CreatesModuleEnvironment::$databaseUser private
Definition at line 83 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getDatabaseUser(), and BristolSU\Support\Testing\CreatesModuleEnvironment\setDatabaseUser().
$for
BristolSU\Support\Testing\CreatesModuleEnvironment::$for private
Definition at line 55 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getModuleIsFor(), and BristolSU\Support\Testing\CreatesModuleEnvironment\setModuleIsFor().
$moduleInstance
BristolSU\Support\Testing\CreatesModuleEnvironment::$moduleInstance private
Definition at line 39 of file CreatesModuleEnvironment.php.
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\getModuleInstance(), and BristolSU\Support\Testing\CreatesModuleEnvironment\setModuleInstance().
The documentation for this class was generated from the following file:
src/Testing/CreatesModuleEnvironment.php