Bristol SU Support Package: BristolSU\Support\User\UserRepository Class Reference
BristolSU\Support\User\UserRepository Class Reference
Public Member Functions
all ()
getFromControlId (int $controlId)
create (array $attributes)
getWhereEmail ($email)
getFromRememberToken (string $token)
getById (int $id)
setRememberToken (int $id, $token)
Detailed Description
Handles retrieving and setting users.
Definition at line 13 of file UserRepository.php.
Member Function Documentation
all()
BristolSU\Support\User\UserRepository::all ()
Get all users registered in the database
Returns
User[]|Collection
Implements BristolSU\Support\User\Contracts\UserRepository.
Definition at line 21 of file UserRepository.php.
create()
BristolSU\Support\User\UserRepository::create (array $attributes)
Create a user.
Attributes should be those in the database [ 'control_id' => 1, // ID of the control user model representing the user ];
Parameters
array $attributes Attributes to create the user with
Returns
User
Implements BristolSU\Support\User\Contracts\UserRepository.
Definition at line 49 of file UserRepository.php.
getById()
BristolSU\Support\User\UserRepository::getById (int $id)
Implements BristolSU\Support\User\Contracts\UserRepository.
Definition at line 83 of file UserRepository.php.
Referenced by BristolSU\Support\User\UserRepository\setRememberToken().
getFromControlId()
BristolSU\Support\User\UserRepository::getFromControlId (int $controlId)
Get a user matching the given control ID
Parameters
int $controlId Control ID of the user
Returns
User
Exceptions
ModelNotFoundException
Implements BristolSU\Support\User\Contracts\UserRepository.
Definition at line 33 of file UserRepository.php.
Referenced by BristolSU\Support\User\UserRepository\getWhereEmail().
getFromRememberToken()
BristolSU\Support\User\UserRepository::getFromRememberToken (string $token)
Get a user by remember token
Parameters
string $token Remember token
Returns
User
Exceptions
ModelNotFoundException
Implements BristolSU\Support\User\Contracts\UserRepository.
Definition at line 75 of file UserRepository.php.
getWhereEmail()
BristolSU\Support\User\UserRepository::getWhereEmail ($email)
Get a user matching the given email address
Parameters
string $email Email address of the user
Returns
User
Exceptions
ModelNotFoundException
Implements BristolSU\Support\User\Contracts\UserRepository.
Definition at line 61 of file UserRepository.php.
References BristolSU\Support\User\UserRepository\getFromControlId().
setRememberToken()
BristolSU\Support\User\UserRepository::setRememberToken (int $id, $token)
Set the remember token of a user
Parameters
int $id ID of the user
mixed $token New token for the user
Implements BristolSU\Support\User\Contracts\UserRepository.
Definition at line 94 of file UserRepository.php.
References BristolSU\Support\User\UserRepository\getById().
The documentation for this class was generated from the following file:
src/User/UserRepository.php