Bristol SU Support Package: BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider Class Reference
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider Class Reference
Public Member Functions
__construct (ActivityInstanceRepository $repository)
retrieveById ($identifier)
retrieveByToken ($identifier, $token)
updateRememberToken (Authenticatable $activityInstance, $token)
retrieveByCredentials (array $credentials)
validateCredentials (Authenticatable $user, array $credentials)
Private Attributes
$repository
Detailed Description
Provider for the current Activity Instance
Definition at line 13 of file ActivityInstanceProvider.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider::__construct (ActivityInstanceRepository $repository)
Initialise the Activity Instance provider
Parameters
ActivityInstanceRepository $repository Repository from which to retrieve the activity instances
Definition at line 28 of file ActivityInstanceProvider.php.
References BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider\$repository.
Member Function Documentation
retrieveByCredentials()
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider::retrieveByCredentials (array $credentials)
Retrieve an Activity Instance by the credentials.
When given correct credentials, will return the Activity Instance. e.g. $credentials = [ 'activity_instance_id' => 1 ]
Parameters
array $credentials
Returns
ActivityInstance|null
Todo:
Make this method take additional credentials for security (if necessary)
Definition at line 83 of file ActivityInstanceProvider.php.
References BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider\retrieveById().
retrieveById()
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider::retrieveById ($identifier)
Retrieve an Activity Instance by ID
Parameters
mixed $identifier
Returns
ActivityInstance|null
Definition at line 39 of file ActivityInstanceProvider.php.
Referenced by BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider\retrieveByCredentials(), and BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider\validateCredentials().
retrieveByToken()
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider::retrieveByToken ($identifier, $token)
Retrieve an Activity Instance by the remember token
Parameters
mixed $identifier ID of the activity instance
string $token Remember Token the activity instance needs to have
Returns
Authenticatable|void|null
Todo:
Implement retrieveByToken method for Activity Instance
Definition at line 53 of file ActivityInstanceProvider.php.
updateRememberToken()
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider::updateRememberToken (Authenticatable $activityInstance, $token)
Update the remember token for the Activity Instance
Parameters
Authenticatable $activityInstance Activity Instance
string $token New remember token to be set
Returns
null
Todo:
Implement updateRememberToken method for Activity Instance
Definition at line 66 of file ActivityInstanceProvider.php.
validateCredentials()
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider::validateCredentials (Authenticatable $user, array $credentials)
Check the credentials for the Activity Instance.
Returns true if credentials are valid. Credentials should look like [ 'activity_instance_id' => 1 ]
Parameters
Authenticatable $user The Activity Instance to validate the credentials against
array $credentials Credentials to test against the Activity Instance
Returns
bool If the credentials are valid
Definition at line 107 of file ActivityInstanceProvider.php.
References BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider\retrieveById().
Member Data Documentation
$repository
BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider::$repository private
Definition at line 21 of file ActivityInstanceProvider.php.
Referenced by BristolSU\Support\ActivityInstance\AuthenticationProvider\ActivityInstanceProvider\__construct().
The documentation for this class was generated from the following file:
src/ActivityInstance/AuthenticationProvider/ActivityInstanceProvider.php