Bristol SU Support Package: BristolSU\Support\Authentication\AuthenticationProvider\UserProvider Class Reference
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider Class Reference
Public Member Functions
__construct (UserRepositoryContract $users)
retrieveById ($identifier)
retrieveByToken ($identifier, $token)
updateRememberToken (Authenticatable $user, $token)
retrieveByCredentials (array $credentials)
validateCredentials (Authenticatable $user, array $credentials)
Private Attributes
$users
Detailed Description
User authentication provider
Definition at line 19 of file UserProvider.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider::__construct (UserRepositoryContract $users)
Initialise the user provider
Parameters
UserRepositoryContract $user User repository contract to retrieve the user from
Definition at line 34 of file UserProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\UserProvider\$users.
Member Function Documentation
retrieveByCredentials()
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider::retrieveByCredentials (array $credentials)
Retrieve a user by ID
Credentials: [ 'user_id' => 1 ]
Parameters
array $credentials Credentials containing the user id
Returns
User|null
Definition at line 84 of file UserProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\UserProvider\retrieveById().
retrieveById()
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider::retrieveById ($identifier)
Get a user by ID
Parameters
mixed $identifier ID of the user
Returns
User|null
Definition at line 45 of file UserProvider.php.
Referenced by BristolSU\Support\Authentication\AuthenticationProvider\UserProvider\retrieveByCredentials(), and BristolSU\Support\Authentication\AuthenticationProvider\UserProvider\validateCredentials().
retrieveByToken()
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider::retrieveByToken ($identifier, $token)
Get a user by the remember token
Parameters
mixed $identifier ID of the user
string $token Remember token of the user
Returns
User|null
Todo:
Implement method
Definition at line 57 of file UserProvider.php.
updateRememberToken()
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider::updateRememberToken (Authenticatable $user, $token)
Update the remember token for the given user
Parameters
Authenticatable $user User to update the token on
string $token Token to update
Todo:
Implement method
Definition at line 68 of file UserProvider.php.
validateCredentials()
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider::validateCredentials (Authenticatable $user, array $credentials)
Ensure the user credentials are valid for the given user
$credentials = [ 'user_id' => 1 ]
Parameters
Authenticatable $user User to validate against
array $credentials Credentials containing the user id
Returns
bool
Todo:
Validate credentials using actual credentials
Definition at line 102 of file UserProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\UserProvider\retrieveById().
Member Data Documentation
$users
BristolSU\Support\Authentication\AuthenticationProvider\UserProvider::$users private
Definition at line 27 of file UserProvider.php.
Referenced by BristolSU\Support\Authentication\AuthenticationProvider\UserProvider\__construct().
The documentation for this class was generated from the following file:
src/Authentication/AuthenticationProvider/UserProvider.php