Bristol SU Support Package: BristolSU\Support\SupportServiceProvider Class Reference
BristolSU\Support\SupportServiceProvider Class Reference
Public Member Functions
register ()
registerProviders ()
registerConfig ()
registerMigrations ()
registerViews ()
registerRoutes ()
Protected Attributes
$providers
Detailed Description
Definition at line 28 of file SupportServiceProvider.php.
Member Function Documentation
register()
BristolSU\Support\SupportServiceProvider::register ()
Definition at line 53 of file SupportServiceProvider.php.
References BristolSU\Support\SupportServiceProvider\registerConfig(), BristolSU\Support\SupportServiceProvider\registerMigrations(), BristolSU\Support\SupportServiceProvider\registerProviders(), BristolSU\Support\SupportServiceProvider\registerRoutes(), and BristolSU\Support\SupportServiceProvider\registerViews().
registerConfig()
BristolSU\Support\SupportServiceProvider::registerConfig ()
Definition at line 69 of file SupportServiceProvider.php.
Referenced by BristolSU\Support\SupportServiceProvider\register().
registerMigrations()
BristolSU\Support\SupportServiceProvider::registerMigrations ()
Definition at line 75 of file SupportServiceProvider.php.
Referenced by BristolSU\Support\SupportServiceProvider\register().
registerProviders()
BristolSU\Support\SupportServiceProvider::registerProviders ()
Definition at line 62 of file SupportServiceProvider.php.
Referenced by BristolSU\Support\SupportServiceProvider\register().
registerRoutes()
BristolSU\Support\SupportServiceProvider::registerRoutes ()
Definition at line 89 of file SupportServiceProvider.php.
Referenced by BristolSU\Support\SupportServiceProvider\register().
registerViews()
BristolSU\Support\SupportServiceProvider::registerViews ()
Definition at line 80 of file SupportServiceProvider.php.
Referenced by BristolSU\Support\SupportServiceProvider\register().
Member Data Documentation
$providers
BristolSU\Support\SupportServiceProvider::$providers protected
Initial value:
= [
        ActionServiceProvider::class,
        ActivityServiceProvider::class,
        EventsServiceProvider::class,
        ActivityInstanceServiceProvider::class,
        AuthorizationServiceProvider::class,
        CompletionConditionServiceProvider::class,
        ConnectionServiceProvider::class,
        UnionCloudServiceProvider::class,
        FilterServiceProvider::class,
        LogicServiceProvider::class,
        PermissionServiceProvider::class,
        AuthenticationServiceProvider::class,
        ModuleFrameworkServiceProvider::class,
        ModuleInstanceServiceProvider::class,
        UserServiceProvider::class,
        HttpServiceProvider::class
    ]
Definition at line 34 of file SupportServiceProvider.php.
The documentation for this class was generated from the following file:
src/SupportServiceProvider.php