Bristol SU Support Package: BristolSU\Support\Module\ModuleManager Class Reference
BristolSU\Support\Module\ModuleManager Class Reference
Public Member Functions
register ($alias)
aliases ()
exists (string $alias)
Protected Attributes
$aliases = []
Detailed Description
Stores module registration information in an array
Definition at line 10 of file ModuleManager.php.
Member Function Documentation
aliases()
BristolSU\Support\Module\ModuleManager::aliases ()
Get all registered aliases
Returns
array
Implements BristolSU\Support\Module\Contracts\ModuleManager.
Definition at line 38 of file ModuleManager.php.
exists()
BristolSU\Support\Module\ModuleManager::exists (string $alias)
Check if a module has been registered
Parameters
string $alias Alias of the module
Returns
bool If the module has been registered
Implements BristolSU\Support\Module\Contracts\ModuleManager.
Definition at line 49 of file ModuleManager.php.
References BristolSU\Support\Module\Contracts\ModuleManager\aliases().
register()
BristolSU\Support\Module\ModuleManager::register ($alias)
Register a new module by alias
Parameters
string $alias Alias of the module
Returns
void
Implements BristolSU\Support\Module\Contracts\ModuleManager.
Definition at line 26 of file ModuleManager.php.
References BristolSU\Support\Module\Contracts\ModuleManager\aliases(), and BristolSU\Support\Module\Contracts\ModuleManager\exists().
Member Data Documentation
$aliases
BristolSU\Support\Module\ModuleManager::$aliases = [] protected
Definition at line 18 of file ModuleManager.php.
The documentation for this class was generated from the following file:
src/Module/ModuleManager.php