Bristol SU Support Package: BristolSU\Support\Module\ModuleBuilder Class Reference
BristolSU\Support\Module\ModuleBuilder Class Reference
Public Member Functions
__construct (ModuleContract $module, PermissionRepository $permissionRepository, Repository $config, EventRepository $eventRepository, CompletionConditionRepository $completionConditionRepository, ModuleSettingsStore $moduleSettingsStore, ServiceRequest $serviceRequest)
create (string $alias)
setAlias ()
setPermissions ()
setName ()
setDescription ()
setSettings ()
setTriggers ()
setServices ()
getModule ()
setCompletionConditions ()
Protected Member Functions
getAlias ()
Private Attributes
$module
$permissionRepository
$config
$alias
$eventRepository
$completionConditionRepository
$moduleSettingsStore
$serviceRequest
Detailed Description
Handles building a module using the framework tools
Definition at line 21 of file ModuleBuilder.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Module\ModuleBuilder::__construct (ModuleContract $module, PermissionRepository $permissionRepository, Repository $config, EventRepository $eventRepository, CompletionConditionRepository $completionConditionRepository, ModuleSettingsStore $moduleSettingsStore, ServiceRequest $serviceRequest)
Parameters
ModuleContract $module Module object to build
PermissionRepository $permissionRepository Repository for resolving permissions
Repository $config Configuration for resolving name/description
EventRepository $eventRepository Repository for resolving events from
CompletionConditionRepository $completionConditionRepository Repository for resolving completion conditions used by the module
ModuleSettingsStore $moduleSettingsStore Store for resolving module settings out of
ServiceRequest $serviceRequest Service request for resolving services needed by the module
Definition at line 90 of file ModuleBuilder.php.
References BristolSU\Support\Module\ModuleBuilder\$completionConditionRepository, BristolSU\Support\Module\ModuleBuilder\$config, BristolSU\Support\Module\ModuleBuilder\$eventRepository, BristolSU\Support\Module\ModuleBuilder\$module, BristolSU\Support\Module\ModuleBuilder\$moduleSettingsStore, BristolSU\Support\Module\ModuleBuilder\$permissionRepository, and BristolSU\Support\Module\ModuleBuilder\$serviceRequest.
Member Function Documentation
create()
BristolSU\Support\Module\ModuleBuilder::create (string $alias)
Initialise the module builder
Parameters
string $alias Alias to use for the module
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 112 of file ModuleBuilder.php.
References BristolSU\Support\Module\ModuleBuilder\$alias, and function\alias().
getAlias()
BristolSU\Support\Module\ModuleBuilder::getAlias () protected
Get the alias to use for the module
Returns
string Alias
Exceptions
Exception If the create() function has not been called, so no alias is known
Definition at line 123 of file ModuleBuilder.php.
References BristolSU\Support\Module\ModuleBuilder\$alias, and function\alias().
Referenced by BristolSU\Support\Module\ModuleBuilder\setAlias(), and BristolSU\Support\Module\ModuleBuilder\setTriggers().
getModule()
BristolSU\Support\Module\ModuleBuilder::getModule ()
Get the built module
Returns
ModuleContract Initialised module
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 225 of file ModuleBuilder.php.
References BristolSU\Support\Module\ModuleBuilder\$module.
setAlias()
BristolSU\Support\Module\ModuleBuilder::setAlias ()
Set the alias on the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 136 of file ModuleBuilder.php.
References BristolSU\Support\Module\ModuleBuilder\getAlias().
setCompletionConditions()
BristolSU\Support\Module\ModuleBuilder::setCompletionConditions ()
Set the completion conditions for the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 235 of file ModuleBuilder.php.
References BristolSU\Support\Completion\Contracts\CompletionCondition\alias(), BristolSU\Support\Completion\Contracts\CompletionCondition\description(), BristolSU\Support\Completion\Contracts\CompletionCondition\name(), and BristolSU\Support\Completion\Contracts\CompletionCondition\options().
setDescription()
BristolSU\Support\Module\ModuleBuilder::setDescription ()
Set the description of the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 170 of file ModuleBuilder.php.
setName()
BristolSU\Support\Module\ModuleBuilder::setName ()
Set the name of the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 158 of file ModuleBuilder.php.
setPermissions()
BristolSU\Support\Module\ModuleBuilder::setPermissions ()
Set the permissions on the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 146 of file ModuleBuilder.php.
setServices()
BristolSU\Support\Module\ModuleBuilder::setServices ()
Set the services of the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 212 of file ModuleBuilder.php.
setSettings()
BristolSU\Support\Module\ModuleBuilder::setSettings ()
Set the settings of the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 182 of file ModuleBuilder.php.
setTriggers()
BristolSU\Support\Module\ModuleBuilder::setTriggers ()
Set the triggers of the module
Exceptions
Exception If no alias is known by the builder
Implements BristolSU\Support\Module\Contracts\ModuleBuilder.
Definition at line 196 of file ModuleBuilder.php.
References BristolSU\Support\Module\ModuleBuilder\getAlias().
Member Data Documentation
$alias
BristolSU\Support\Module\ModuleBuilder::$alias private
Definition at line 51 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\create(), and BristolSU\Support\Module\ModuleBuilder\getAlias().
$completionConditionRepository
BristolSU\Support\Module\ModuleBuilder::$completionConditionRepository private
Definition at line 65 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\__construct().
$config
BristolSU\Support\Module\ModuleBuilder::$config private
Todo:
Register the name and description of the module in the service provider
Definition at line 44 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\__construct().
$eventRepository
BristolSU\Support\Module\ModuleBuilder::$eventRepository private
Definition at line 58 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\__construct().
$module
BristolSU\Support\Module\ModuleBuilder::$module private
Definition at line 29 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\__construct(), and BristolSU\Support\Module\ModuleBuilder\getModule().
$moduleSettingsStore
BristolSU\Support\Module\ModuleBuilder::$moduleSettingsStore private
Definition at line 72 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\__construct().
$permissionRepository
BristolSU\Support\Module\ModuleBuilder::$permissionRepository private
Definition at line 36 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\__construct().
$serviceRequest
BristolSU\Support\Module\ModuleBuilder::$serviceRequest private
Definition at line 79 of file ModuleBuilder.php.
Referenced by BristolSU\Support\Module\ModuleBuilder\__construct().
The documentation for this class was generated from the following file:
src/Module/ModuleBuilder.php