Bristol SU Support Package: BristolSU\Support\Filters\Jobs\CacheFilter Class Reference
BristolSU\Support\Filters\Jobs\CacheFilter Class Reference
Public Member Functions
filterInstance ()
model ()
__construct (FilterInstance $filterInstance, $model)
handle (FilterTester $filterTester)
Private Attributes
$filterInstance
$model
Detailed Description
Job to cache a filter result
Definition at line 16 of file CacheFilter.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Filters\Jobs\CacheFilter::__construct (FilterInstance $filterInstance, $model)
Parameters
FilterInstance $filterInstance Filter instance to resolve the filter from
User | Group | Role $model Model to test the filter against
Definition at line 58 of file CacheFilter.php.
References BristolSU\Support\Filters\Jobs\CacheFilter\$filterInstance, BristolSU\Support\Filters\Jobs\CacheFilter\$model, BristolSU\Support\Filters\Jobs\CacheFilter\filterInstance(), and BristolSU\Support\Filters\Jobs\CacheFilter\model().
Member Function Documentation
filterInstance()
BristolSU\Support\Filters\Jobs\CacheFilter::filterInstance ()
Get the filter instance
Returns
FilterInstance
Definition at line 39 of file CacheFilter.php.
References BristolSU\Support\Filters\Jobs\CacheFilter\$filterInstance.
Referenced by BristolSU\Support\Filters\Jobs\CacheFilter\__construct(), and BristolSU\Support\Filters\Jobs\CacheFilter\handle().
handle()
BristolSU\Support\Filters\Jobs\CacheFilter::handle (FilterTester $filterTester)
Handle the job
Test the filter. If the cached decorator is bound to the container, the result will be cached
Parameters
FilterTester $filterTester Filter tester to test the result with. It should cache the result
Exceptions
Definition at line 72 of file CacheFilter.php.
References BristolSU\Support\Filters\Contracts\FilterTester\evaluate(), BristolSU\Support\Filters\Jobs\CacheFilter\filterInstance(), and BristolSU\Support\Filters\Jobs\CacheFilter\model().
model()
BristolSU\Support\Filters\Jobs\CacheFilter::model ()
Get the model
Returns
Group|Role|User
Definition at line 49 of file CacheFilter.php.
References BristolSU\Support\Filters\Jobs\CacheFilter\$model.
Referenced by BristolSU\Support\Filters\Jobs\CacheFilter\__construct(), and BristolSU\Support\Filters\Jobs\CacheFilter\handle().
Member Data Documentation
$filterInstance
BristolSU\Support\Filters\Jobs\CacheFilter::$filterInstance private
Definition at line 25 of file CacheFilter.php.
Referenced by BristolSU\Support\Filters\Jobs\CacheFilter\__construct(), and BristolSU\Support\Filters\Jobs\CacheFilter\filterInstance().
$model
BristolSU\Support\Filters\Jobs\CacheFilter::$model private
Definition at line 32 of file CacheFilter.php.
Referenced by BristolSU\Support\Filters\Jobs\CacheFilter\__construct(), and BristolSU\Support\Filters\Jobs\CacheFilter\model().
The documentation for this class was generated from the following file:
src/Filters/Jobs/CacheFilter.php