Bristol SU Support Package: BristolSU\Support\DataPlatform\Repositories\User Class Reference
BristolSU\Support\DataPlatform\Repositories\User Class Reference
Public Member Functions
__construct (UnionCloud $unionCloud)
getByIdentity ($identity)
getByEmail ($email)
getByStudentID ($studentId)
getById ($id)
Public Member Functions inherited from BristolSU\Support\User\Contracts\UserRepository
getWhereIdentity ($identity)
getWhereEmail ($email)
create (array $attributes)
all ()
Private Attributes
$unionCloud
Detailed Description
Definition at line 16 of file User.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\DataPlatform\Repositories\User::__construct (UnionCloud $unionCloud)
User constructor.
Parameters
UnionCloud $unionCloud
Definition at line 28 of file User.php.
References BristolSU\Support\DataPlatform\Repositories\User\$unionCloud.
Member Function Documentation
getByEmail()
BristolSU\Support\DataPlatform\Repositories\User::getByEmail ($email)
Parameters
$email
Returns
UserModelContract
Exceptions
Definition at line 60 of file User.php.
Referenced by BristolSU\Support\DataPlatform\Repositories\User\getByIdentity().
getById()
BristolSU\Support\DataPlatform\Repositories\User::getById ($id)
Parameters
$id
Returns
UserModelContract
Exceptions
Definition at line 90 of file User.php.
getByIdentity()
BristolSU\Support\DataPlatform\Repositories\User::getByIdentity ($identity)
Parameters
$identity
Returns
UserModelContract
Exceptions
Definition at line 42 of file User.php.
References BristolSU\Support\DataPlatform\Repositories\User\getByEmail(), and BristolSU\Support\DataPlatform\Repositories\User\getByStudentID().
getByStudentID()
BristolSU\Support\DataPlatform\Repositories\User::getByStudentID ($studentId)
Parameters
$studentId
Returns
UserModelContract
Exceptions
Definition at line 75 of file User.php.
Referenced by BristolSU\Support\DataPlatform\Repositories\User\getByIdentity().
Member Data Documentation
$unionCloud
BristolSU\Support\DataPlatform\Repositories\User::$unionCloud private
Definition at line 22 of file User.php.
Referenced by BristolSU\Support\DataPlatform\Repositories\User\__construct().
The documentation for this class was generated from the following file:
src/DataPlatform/Repositories/User.php