Bristol SU Support Package: BristolSU\Support\Logic\LogicTester Class Reference
BristolSU\Support\Logic\LogicTester Class Reference
Public Member Functions
evaluate (Logic $logic, $userModel=null, $groupModel=null, $roleModel=null)
Detailed Description
Definition at line 16 of file LogicTester.php.
Member Function Documentation
evaluate()
BristolSU\Support\Logic\LogicTester::evaluate (Logic $logic, $userModel = null, $groupModel = null, $roleModel = null)
Parameters
Logic $logic
null $userModel
null $groupModel
null $roleModel
Returns
bool
Implements BristolSU\Support\Logic\Contracts\LogicTester.
Definition at line 26 of file LogicTester.php.
References BristolSU\Support\Logic\Logic\allFalseFilters(), BristolSU\Support\Logic\Logic\allTrueFilters(), BristolSU\Support\Logic\Logic\anyFalseFilters(), and BristolSU\Support\Logic\Logic\anyTrueFilters().
Referenced by BristolSU\Support\Logic\Audience\AudienceMember\filterForLogic().
The documentation for this class was generated from the following file:
src/Logic/LogicTester.php