Bristol SU Support Package: BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled Class Reference
BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled Class Reference
Public Member Functions
setModuleInstance (ModuleInstance $moduleInstance)
moduleInstance ()
Static Public Member Functions
static fromModuleInstance (ModuleInstance $moduleInstance)
Protected Attributes
$moduleInstance
Detailed Description
Definition at line 7 of file ModuleInstanceDisabled.php.
Member Function Documentation
fromModuleInstance()
static BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled::fromModuleInstance (ModuleInstance $moduleInstance) static
Create an instance of the exception
Parameters
ModuleInstance $moduleInstance
Returns
ModuleInstanceDisabled
Definition at line 21 of file ModuleInstanceDisabled.php.
Referenced by BristolSU\Support\Authorization\Middleware\CheckModuleInstanceEnabled\handle().
moduleInstance()
BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled::moduleInstance ()
Set the moduleInstance that caused the exception to be thrown
Returns
ModuleInstance
Definition at line 42 of file ModuleInstanceDisabled.php.
References BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled\$moduleInstance.
Referenced by BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled\setModuleInstance().
setModuleInstance()
BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled::setModuleInstance (ModuleInstance $moduleInstance)
Set the moduleInstance that caused the exception to be thrown
Parameters
ModuleInstance $moduleInstance
Definition at line 32 of file ModuleInstanceDisabled.php.
References BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled\$moduleInstance, and BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled\moduleInstance().
Member Data Documentation
$moduleInstance
BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled::$moduleInstance protected
Definition at line 13 of file ModuleInstanceDisabled.php.
Referenced by BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled\moduleInstance(), and BristolSU\Support\Authorization\Exception\ModuleInstanceDisabled\setModuleInstance().
The documentation for this class was generated from the following file:
src/Authorization/Exception/ModuleInstanceDisabled.php