Bristol SU Support Package: BristolSU\Support\ModuleInstance\ModuleInstance Class Reference
BristolSU\Support\ModuleInstance\ModuleInstance Class Reference
Public Member Functions
__construct (array $attributes=[])
alias ()
id ()
activity ()
moduleInstanceSettings ()
moduleInstancePermissions ()
completionConditionInstance ()
activeLogic ()
visibleLogic ()
mandatoryLogic ()
actionInstances ()
moduleInstanceServices ()
setting ($key, $default=null)
Protected Attributes
$fillable
Detailed Description
Definition at line 21 of file ModuleInstance.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\ModuleInstance\ModuleInstance::__construct (array $attributes = [])
ModuleInstance constructor.
Parameters
array $attributes
Definition at line 43 of file ModuleInstance.php.
Member Function Documentation
actionInstances()
BristolSU\Support\ModuleInstance\ModuleInstance::actionInstances ()
Returns
Definition at line 125 of file ModuleInstance.php.
activeLogic()
BristolSU\Support\ModuleInstance\ModuleInstance::activeLogic ()
Returns
Definition at line 101 of file ModuleInstance.php.
activity()
BristolSU\Support\ModuleInstance\ModuleInstance::activity ()
Returns
Definition at line 72 of file ModuleInstance.php.
alias()
BristolSU\Support\ModuleInstance\ModuleInstance::alias ()
Returns
mixed
Implements BristolSU\Support\ModuleInstance\Contracts\ModuleInstance.
Definition at line 56 of file ModuleInstance.php.
Referenced by BristolSU\Support\Http\Controllers\ModuleInstanceRedirectController\index().
completionConditionInstance()
BristolSU\Support\ModuleInstance\ModuleInstance::completionConditionInstance ()
Definition at line 93 of file ModuleInstance.php.
id()
BristolSU\Support\ModuleInstance\ModuleInstance::id ()
Returns
mixed
Implements BristolSU\Support\ModuleInstance\Contracts\ModuleInstance.
Definition at line 64 of file ModuleInstance.php.
mandatoryLogic()
BristolSU\Support\ModuleInstance\ModuleInstance::mandatoryLogic ()
Returns
Definition at line 117 of file ModuleInstance.php.
moduleInstancePermissions()
BristolSU\Support\ModuleInstance\ModuleInstance::moduleInstancePermissions ()
Returns
Definition at line 88 of file ModuleInstance.php.
moduleInstanceServices()
BristolSU\Support\ModuleInstance\ModuleInstance::moduleInstanceServices ()
Definition at line 130 of file ModuleInstance.php.
moduleInstanceSettings()
BristolSU\Support\ModuleInstance\ModuleInstance::moduleInstanceSettings ()
Returns
Definition at line 80 of file ModuleInstance.php.
Referenced by BristolSU\Support\ModuleInstance\ModuleInstance\setting().
setting()
BristolSU\Support\ModuleInstance\ModuleInstance::setting ($key, $default = null)
Definition at line 135 of file ModuleInstance.php.
References BristolSU\Support\ModuleInstance\ModuleInstance\moduleInstanceSettings().
visibleLogic()
BristolSU\Support\ModuleInstance\ModuleInstance::visibleLogic ()
Returns
Definition at line 109 of file ModuleInstance.php.
Member Data Documentation
$fillable
BristolSU\Support\ModuleInstance\ModuleInstance::$fillable protected
Initial value:
= [
        'alias',
        'activity_id',
        'name',
        'slug',
        'description',
        'active',
        'visible',
        'mandatory',
        'completion_condition_instance_id'
    ]
Definition at line 27 of file ModuleInstance.php.
The documentation for this class was generated from the following file:
src/ModuleInstance/ModuleInstance.php