Bristol SU Support Package: BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider Class Reference
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider Class Reference
Public Member Functions
__construct (GroupRepositoryContract $groups)
retrieveById ($identifier)
retrieveByToken ($identifier, $token)
updateRememberToken (Authenticatable $group, $token)
retrieveByCredentials (array $credentials)
validateCredentials (Authenticatable $group, array $credentials)
Public Member Functions inherited from BristolSU\Support\Authentication\AuthenticationProvider\UserProvider
__construct (UserRepositoryContract $users)
retrieveById ($identifier)
retrieveByToken ($identifier, $token)
updateRememberToken (Authenticatable $user, $token)
retrieveByCredentials (array $credentials)
validateCredentials (Authenticatable $user, array $credentials)
Private Attributes
$groups
Detailed Description
Group authentication provider
Definition at line 19 of file GroupProvider.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider::__construct (GroupRepositoryContract $groups)
Initialise the group provider
Parameters
GroupRepositoryContract $groups
Definition at line 34 of file GroupProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider\$groups.
Member Function Documentation
retrieveByCredentials()
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider::retrieveByCredentials (array $credentials)
Retrieve a group by credentials
Credentials should be an array such as [ 'group_id' => 1 ]
Parameters
array $credentials Credentials to retrieve the group with
Returns
Group|null
Definition at line 85 of file GroupProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider\retrieveById().
retrieveById()
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider::retrieveById ($identifier)
Get the group by ID
Parameters
mixed $identifier ID of the group
Returns
Group|null Group with the id given
Definition at line 45 of file GroupProvider.php.
Referenced by BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider\retrieveByCredentials(), and BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider\validateCredentials().
retrieveByToken()
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider::retrieveByToken ($identifier, $token)
Get the group by a remember token
Parameters
mixed $identifier ID of the group
string $token Remember token
Returns
Group|null
Definition at line 57 of file GroupProvider.php.
updateRememberToken()
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider::updateRememberToken (Authenticatable $group, $token)
Update the group remember token
Parameters
Authenticatable $group Group to set the remember token on
string $token Remember token to set
Returns
void
Todo:
Implement method
Definition at line 69 of file GroupProvider.php.
validateCredentials()
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider::validateCredentials (Authenticatable $group, array $credentials)
Ensure the group is accessible by the user
Credentials should be an array: [ 'group_id' => 1 ]
Parameters
Authenticatable $group Group to validate against
array $credentials Credentials to validate
Returns
bool Are the credentials valid
Todo:
Validate credentials using actual credentials
Definition at line 106 of file GroupProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider\retrieveById().
Member Data Documentation
$groups
BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider::$groups private
Definition at line 27 of file GroupProvider.php.
Referenced by BristolSU\Support\Authentication\AuthenticationProvider\GroupProvider\__construct().
The documentation for this class was generated from the following file:
src/Authentication/AuthenticationProvider/GroupProvider.php