Bristol SU Support Package: BristolSU\Support\Action\History\HasHistory Class Reference
BristolSU\Support\Action\History\HasHistory Class Reference
Public Member Functions
setActionInstanceId (int $actionInstanceId)
setEventFields (array $eventFields)
setSettings (array $settings)
saveHistory (ActionResponse $response)
Private Attributes
$actionInstanceId
$eventFields
$settings
Detailed Description
Definition at line 9 of file HasHistory.php.
Member Function Documentation
saveHistory()
BristolSU\Support\Action\History\HasHistory::saveHistory (ActionResponse $response)
Save the history of the action run
Parameters
ActionResponse $response Response of the run
Exceptions
Exception If the action instance ID is not given
Definition at line 69 of file HasHistory.php.
References BristolSU\Support\Action\ActionResponse\getMessage(), BristolSU\Support\Action\ActionResponse\getSuccess(), and function\settings().
setActionInstanceId()
BristolSU\Support\Action\History\HasHistory::setActionInstanceId (int $actionInstanceId)
Set the action instance for use in the action history records
Parameters
int $actionInstanceId
Definition at line 38 of file HasHistory.php.
References BristolSU\Support\Action\History\HasHistory\$actionInstanceId.
setEventFields()
BristolSU\Support\Action\History\HasHistory::setEventFields (array $eventFields)
Set the fields given by the event
Parameters
array $eventFields
Definition at line 48 of file HasHistory.php.
References BristolSU\Support\Action\History\HasHistory\$eventFields.
setSettings()
BristolSU\Support\Action\History\HasHistory::setSettings (array $settings)
Set the data passed to the action
Parameters
array $settings
Definition at line 58 of file HasHistory.php.
References BristolSU\Support\Action\History\HasHistory\$settings, and function\settings().
Member Data Documentation
$actionInstanceId
BristolSU\Support\Action\History\HasHistory::$actionInstanceId private
Definition at line 17 of file HasHistory.php.
Referenced by BristolSU\Support\Action\History\HasHistory\setActionInstanceId().
$eventFields
BristolSU\Support\Action\History\HasHistory::$eventFields private
Definition at line 24 of file HasHistory.php.
Referenced by BristolSU\Support\Action\History\HasHistory\setEventFields().
$settings
BristolSU\Support\Action\History\HasHistory::$settings private
Definition at line 31 of file HasHistory.php.
Referenced by BristolSU\Support\Action\History\HasHistory\setSettings().
The documentation for this class was generated from the following file:
src/Action/History/HasHistory.php