Bristol SU Support Package: BristolSU\Support\Completion\CompletionConditionInstance Class Reference
BristolSU\Support\Completion\CompletionConditionInstance Class Reference
Public Member Functions
name ()
settings ()
alias ()
moduleInstance ()
Protected Attributes
$fillable
$casts
Detailed Description
Represents a completion condition instance
Definition at line 14 of file CompletionConditionInstance.php.
Member Function Documentation
alias()
BristolSU\Support\Completion\CompletionConditionInstance::alias ()
Get the alias of the completion condition instance
Returns
string
Implements BristolSU\Support\Completion\Contracts\CompletionConditionInstance.
Definition at line 60 of file CompletionConditionInstance.php.
Referenced by BristolSU\Support\Completion\CompletionConditionTester\evaluate().
moduleInstance()
BristolSU\Support\Completion\CompletionConditionInstance::moduleInstance ()
Module instance relationship
Returns
Definition at line 70 of file CompletionConditionInstance.php.
Referenced by BristolSU\Support\Completion\CompletionConditionTester\evaluate().
name()
BristolSU\Support\Completion\CompletionConditionInstance::name ()
Get the name of the completion condition instance
Returns
string
Implements BristolSU\Support\Completion\Contracts\CompletionConditionInstance.
Definition at line 40 of file CompletionConditionInstance.php.
settings()
BristolSU\Support\Completion\CompletionConditionInstance::settings ()
Get the settings for the completion condition instance
Returns
array
Implements BristolSU\Support\Completion\Contracts\CompletionConditionInstance.
Definition at line 50 of file CompletionConditionInstance.php.
Referenced by BristolSU\Support\Completion\CompletionConditionTester\evaluate().
Member Data Documentation
$casts
BristolSU\Support\Completion\CompletionConditionInstance::$casts protected
Initial value:
= [
        'settings' => 'array'
    ]
Definition at line 31 of file CompletionConditionInstance.php.
$fillable
BristolSU\Support\Completion\CompletionConditionInstance::$fillable protected
Initial value:
= [
        'alias', 'name', 'settings', 'description'
    ]
Definition at line 22 of file CompletionConditionInstance.php.
The documentation for this class was generated from the following file:
src/Completion/CompletionConditionInstance.php