Bristol SU Support Package: BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider Class Reference
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider Class Reference
Public Member Functions
__construct (RoleContract $role)
retrieveById ($identifier)
retrieveByToken ($identifier, $token)
updateRememberToken (Authenticatable $role, $token)
retrieveByCredentials (array $credentials)
validateCredentials (Authenticatable $role, array $credentials)
Public Member Functions inherited from BristolSU\Support\Authentication\AuthenticationProvider\UserProvider
__construct (UserRepositoryContract $users)
retrieveById ($identifier)
retrieveByToken ($identifier, $token)
updateRememberToken (Authenticatable $user, $token)
retrieveByCredentials (array $credentials)
validateCredentials (Authenticatable $user, array $credentials)
Private Attributes
$role
Detailed Description
Role authentication provider
Definition at line 19 of file RoleProvider.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider::__construct (RoleContract $role)
Initialise the role provider
Parameters
RoleContract $role Role repository contract to retrieve the role from
Definition at line 34 of file RoleProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider\$role.
Member Function Documentation
retrieveByCredentials()
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider::retrieveByCredentials (array $credentials)
Retrieve a role by ID
Credentials: [ 'role_id' => 1 ]
Parameters
array $credentials Credentials containing the role id
Returns
Role|null
Definition at line 86 of file RoleProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider\retrieveById().
retrieveById()
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider::retrieveById ($identifier)
Get a role by ID
Parameters
mixed $identifier ID of the role
Returns
Role|null
Definition at line 45 of file RoleProvider.php.
Referenced by BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider\retrieveByCredentials(), and BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider\validateCredentials().
retrieveByToken()
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider::retrieveByToken ($identifier, $token)
Get a role by the remember token
Parameters
mixed $identifier ID of the role
string $token Remember token of the role
Returns
Role|null
Todo:
Implement method
Definition at line 58 of file RoleProvider.php.
updateRememberToken()
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider::updateRememberToken (Authenticatable $role, $token)
Update the remember token for the given role
Parameters
Authenticatable $role Role to update the token on
string $token Token to update
Todo:
Implement method
Definition at line 70 of file RoleProvider.php.
validateCredentials()
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider::validateCredentials (Authenticatable $role, array $credentials)
Ensure the role credentials are valid for the given role
$credentials = [ 'role_id' => 1 ]
Parameters
Authenticatable $role Role to validate against
array $credentials Credentials containing the role id
Returns
bool
Todo:
Validate credentials using actual credentials
Definition at line 104 of file RoleProvider.php.
References BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider\retrieveById().
Member Data Documentation
$role
BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider::$role private
Definition at line 27 of file RoleProvider.php.
Referenced by BristolSU\Support\Authentication\AuthenticationProvider\RoleProvider\__construct().
The documentation for this class was generated from the following file:
src/Authentication/AuthenticationProvider/RoleProvider.php