Bristol SU Support Package: BristolSU\Support\Completion\CompletionConditionTester Class Reference
BristolSU\Support\Completion\CompletionConditionTester Class Reference
Public Member Functions
__construct (CompletionConditionRepository $repository)
evaluate (ActivityInstance $activityInstance, CompletionConditionInstance $completionConditionInstance)
Public Member Functions inherited from BristolSU\Support\Completion\Contracts\CompletionConditionTester
evaluate (ActivityInstance $activityInstance, CompletionConditionInstance $completionConditionInstance)
Private Attributes
$repository
Detailed Description
Test if a module instance is complete
Definition at line 17 of file CompletionConditionTester.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Completion\CompletionConditionTester::__construct (CompletionConditionRepository $repository)
Parameters
CompletionConditionRepository $repository
Definition at line 29 of file CompletionConditionTester.php.
References BristolSU\Support\Completion\CompletionConditionTester\$repository.
Member Function Documentation
evaluate()
BristolSU\Support\Completion\CompletionConditionTester::evaluate (ActivityInstance $activityInstance, CompletionConditionInstance $completionConditionInstance)
Check if the completion condition is complete for the given activity instance
Parameters
ActivityInstance $activityInstance Activity instance to test
CompletionConditionInstance $completionConditionInstance Completion condition instance to test
Returns
bool If the completion condition is complete
Definition at line 42 of file CompletionConditionTester.php.
References BristolSU\Support\Completion\CompletionConditionInstance\alias(), BristolSU\Support\Completion\CompletionConditionInstance\moduleInstance(), and BristolSU\Support\Completion\CompletionConditionInstance\settings().
Member Data Documentation
$repository
BristolSU\Support\Completion\CompletionConditionTester::$repository private
Definition at line 24 of file CompletionConditionTester.php.
Referenced by BristolSU\Support\Completion\CompletionConditionTester\__construct().
The documentation for this class was generated from the following file:
src/Completion/CompletionConditionTester.php