Bristol SU Support Package: BristolSU\Support\ModuleInstance\Evaluator\Evaluation Class Reference
BristolSU\Support\ModuleInstance\Evaluator\Evaluation Class Reference
Public Member Functions
active ()
mandatory ()
complete ()
setActive (bool $active)
setMandatory (bool $mandatory)
setVisible (bool $visible)
setComplete (bool $complete)
visible ()
toArray ()
toJson ($options=0)
__toString ()
Private Attributes
$active = false
$visible = false
$mandatory = false
$complete = false
Detailed Description
Represents an evaluation of a module instance
Definition at line 12 of file Evaluation.php.
Member Function Documentation
__toString()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::__toString ()
Convert the object to a JSON representation
Returns
string
Definition at line 158 of file Evaluation.php.
References BristolSU\Support\ModuleInstance\Evaluator\Evaluation\toJson().
active()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::active ()
Is the module instance active?
Returns
bool
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 47 of file Evaluation.php.
complete()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::complete ()
Is the module instance complete?
Returns
bool
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 67 of file Evaluation.php.
mandatory()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::mandatory ()
Is the module instance mandatory?
Returns
bool
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 57 of file Evaluation.php.
setActive()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::setActive (bool $active)
Set the active status of the module instance evaluation
Parameters
bool $active New active status of the module instance evaluation
Returns
void
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 78 of file Evaluation.php.
References BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\active().
setComplete()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::setComplete (bool $complete)
Set the complete status of the module instance evaluation
Parameters
bool $complete Complete status
Returns
void
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 111 of file Evaluation.php.
References BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\complete().
setMandatory()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::setMandatory (bool $mandatory)
Set the mandatory status of the module instance evaluation
Parameters
bool $mandatory Mandatory status
Returns
void
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 89 of file Evaluation.php.
References BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\mandatory().
setVisible()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::setVisible (bool $visible)
Set the visible status of the module instance evaluation
Parameters
bool $visible Visible status
Returns
void
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 100 of file Evaluation.php.
References BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\visible().
toArray()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::toArray ()
Cast the representation to an array
Returns
array
Definition at line 131 of file Evaluation.php.
References BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\active(), BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\complete(), BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\mandatory(), and BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation\visible().
Referenced by BristolSU\Support\ModuleInstance\Evaluator\Evaluation\toJson().
toJson()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::toJson ($options = 0)
Convert the object to its JSON representation.
Parameters
int $options
Returns
string
Definition at line 148 of file Evaluation.php.
References BristolSU\Support\ModuleInstance\Evaluator\Evaluation\toArray().
Referenced by BristolSU\Support\ModuleInstance\Evaluator\Evaluation\__toString().
visible()
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::visible ()
Is the module instance visible?
Returns
bool
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\Evaluation.
Definition at line 121 of file Evaluation.php.
Member Data Documentation
$active
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::$active = false private
Definition at line 19 of file Evaluation.php.
$complete
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::$complete = false private
Definition at line 40 of file Evaluation.php.
$mandatory
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::$mandatory = false private
Definition at line 33 of file Evaluation.php.
$visible
BristolSU\Support\ModuleInstance\Evaluator\Evaluation::$visible = false private
Definition at line 26 of file Evaluation.php.
The documentation for this class was generated from the following file:
src/ModuleInstance/Evaluator/Evaluation.php