Bristol SU Support Package: BristolSU\Support\Filters\Contracts\Filters\Filter Class Reference
BristolSU\Support\Filters\Contracts\Filters\Filter Class Reference
Public Member Functions
model ()
options ()
hasModel ()
setModel ($model)
evaluate ($settings)
name ()
description ()
alias ()
toArray ()
Detailed Description
Represents a filter
Definition at line 17 of file Filter.php.
Member Function Documentation
alias()
BristolSU\Support\Filters\Contracts\Filters\Filter::alias () abstract
Alias of the filter
Returns
string Alias of the filter
Referenced by BristolSU\Support\Filters\Contracts\Filters\Filter\toArray().
description()
BristolSU\Support\Filters\Contracts\Filters\Filter::description () abstract
Description of the filter
Returns
string Description of the filter
Referenced by BristolSU\Support\Filters\Contracts\Filters\Filter\toArray().
evaluate()
BristolSU\Support\Filters\Contracts\Filters\Filter::evaluate ($settings) abstract
Test if the filter passes
Parameters
string $settings Filled in values in the form of options()
Returns
bool Does the filter pass?
hasModel()
BristolSU\Support\Filters\Contracts\Filters\Filter::hasModel () abstract
Does the filter have a model to test?
Returns
bool Does the filter have a model?
model()
BristolSU\Support\Filters\Contracts\Filters\Filter::model () abstract
Get the model for the filter
Returns
User|Group|Role
name()
BristolSU\Support\Filters\Contracts\Filters\Filter::name () abstract
Name of the filter
Returns
string Name of the filter
Referenced by BristolSU\Support\Filters\Contracts\Filters\Filter\toArray().
options()
BristolSU\Support\Filters\Contracts\Filters\Filter::options () abstract
Get possible options as an array
You should return a form schema which represents the available options for the filter
Returns
FormSchema Options
Referenced by BristolSU\Support\Filters\Contracts\Filters\Filter\toArray().
setModel()
BristolSU\Support\Filters\Contracts\Filters\Filter::setModel ($model) abstract
Set a model to use for the filter
Parameters
User | Group | Role $model Model to be used for the filter evaluation
Returns
void
toArray()
BristolSU\Support\Filters\Contracts\Filters\Filter::toArray ()
Cast the filter to an array
Returns
array Filter as an array
Definition at line 86 of file Filter.php.
References BristolSU\Support\Filters\Contracts\Filters\Filter\alias(), BristolSU\Support\Filters\Contracts\Filters\Filter\description(), BristolSU\Support\Filters\Contracts\Filters\Filter\name(), and BristolSU\Support\Filters\Contracts\Filters\Filter\options().
The documentation for this class was generated from the following file:
src/Filters/Contracts/Filters/Filter.php