Bristol SU Support Package: BristolSU\Support\Testing\HandlesAuthorization Class Reference
BristolSU\Support\Testing\HandlesAuthorization Class Reference
Public Member Functions
bypassAuthorization ()
givePermissionTo (string $ability)
revokePermissionTo (string $ability)
Protected Member Functions
getPermissionTester ()
Protected Attributes
$permissionTester
Detailed Description
Trait for aiding interactions with the user/group/role system
Definition at line 13 of file HandlesAuthorization.php.
Member Function Documentation
bypassAuthorization()
BristolSU\Support\Testing\HandlesAuthorization::bypassAuthorization ()
Bypass any authorization checks made in controllers.
This will simply ensure any call to the permission tester 'evaluate' method returns true.
Returns
void
Definition at line 41 of file HandlesAuthorization.php.
References BristolSU\Support\Testing\HandlesAuthorization\getPermissionTester().
getPermissionTester()
BristolSU\Support\Testing\HandlesAuthorization::getPermissionTester () protected
Creates a prophesized permission tester, or returns a previously created one.
Returns
PermissionTester|ObjectProphecy
Definition at line 26 of file HandlesAuthorization.php.
References BristolSU\Support\Testing\HandlesAuthorization\$permissionTester.
Referenced by BristolSU\Support\Testing\HandlesAuthorization\bypassAuthorization(), BristolSU\Support\Testing\HandlesAuthorization\givePermissionTo(), and BristolSU\Support\Testing\HandlesAuthorization\revokePermissionTo().
givePermissionTo()
BristolSU\Support\Testing\HandlesAuthorization::givePermissionTo (string $ability)
Give the permission to the current user
Parameters
string $ability Ability string to give to the user
Returns
void
Definition at line 54 of file HandlesAuthorization.php.
References BristolSU\Support\Testing\HandlesAuthorization\getPermissionTester().
revokePermissionTo()
BristolSU\Support\Testing\HandlesAuthorization::revokePermissionTo (string $ability)
Remove the permission from the current user
Parameters
string $ability Ability string to remove from the user
Returns
void
Definition at line 67 of file HandlesAuthorization.php.
References BristolSU\Support\Testing\HandlesAuthorization\getPermissionTester().
Member Data Documentation
$permissionTester
BristolSU\Support\Testing\HandlesAuthorization::$permissionTester protected
Definition at line 19 of file HandlesAuthorization.php.
Referenced by BristolSU\Support\Testing\HandlesAuthorization\getPermissionTester().
The documentation for this class was generated from the following file:
src/Testing/HandlesAuthorization.php