Bristol SU Support Package: BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator Class Reference
BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator Class Reference
Public Member Functions
__construct (ModuleInstanceEvaluatorContract $moduleInstanceEvaluator)
evaluateAdministrator (ActivityInstance $activityInstance, ?User $user=null, ?Group $group=null, ?Role $role=null)
evaluateParticipant (ActivityInstance $activityInstance, ?User $user=null, ?Group $group=null, ?Role $role=null)
evaluateResource (ActivityInstance $activityInstance)
Private Attributes
$moduleInstanceEvaluator
Detailed Description
Evaluates all module instances belonging to an activity
Definition at line 19 of file ActivityInstanceEvaluator.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator::__construct (ModuleInstanceEvaluatorContract $moduleInstanceEvaluator)
Parameters
ModuleInstanceEvaluatorContract $moduleInstanceEvaluator Object to evaluate module instances
Definition at line 32 of file ActivityInstanceEvaluator.php.
References BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator\$moduleInstanceEvaluator.
Member Function Documentation
evaluateAdministrator()
BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator::evaluateAdministrator (ActivityInstance $activityInstance, ?User $user = null, ?Group $group = null, ?Role $role = null)
Evaluate an activity instance for an administrator
Parameters
ActivityInstance $activityInstance Activity instance to evaluate
User | null $user User to evaluate for
Group | null $group Group to evaluate for
Role | null $role Role to evaluate for
Returns
EvaluationContract[] Array of evaluations with the module instance id as the index
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\ActivityInstanceEvaluator.
Definition at line 47 of file ActivityInstanceEvaluator.php.
References BristolSU\Support\ActivityInstance\ActivityInstance\activity().
evaluateParticipant()
BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator::evaluateParticipant (ActivityInstance $activityInstance, ?User $user = null, ?Group $group = null, ?Role $role = null)
Evaluate an activity instance for a participant
Parameters
ActivityInstance $activityInstance Activity instance to evaluate
User | null $user User to evaluate for
Group | null $group Group to evaluate for
Role | null $role Role to evaluate for
Returns
EvaluationContract[] Array of evaluations with the module instance id as the index
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\ActivityInstanceEvaluator.
Definition at line 65 of file ActivityInstanceEvaluator.php.
References BristolSU\Support\ActivityInstance\ActivityInstance\activity().
evaluateResource()
BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator::evaluateResource (ActivityInstance $activityInstance)
Evaluate the activity instance as a whole
As opposed to the evaluateParticipant and evaluateAdministrator methods, which evaluate an activity instance for a specific user/group/role, evaluateResource will consider all users/groups/roles able to access the activity instance.
Parameters
ActivityInstance $activityInstance Activity to test
Returns
EvaluationContract[] Array of evaluations with the module instance id as the index
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\ActivityInstanceEvaluator.
Definition at line 82 of file ActivityInstanceEvaluator.php.
References BristolSU\Support\ActivityInstance\ActivityInstance\activity().
Member Data Documentation
$moduleInstanceEvaluator
BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator::$moduleInstanceEvaluator private
Definition at line 27 of file ActivityInstanceEvaluator.php.
Referenced by BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator\__construct().
The documentation for this class was generated from the following file:
src/ModuleInstance/Evaluator/ActivityInstanceEvaluator.php