Bristol SU Support Package: BristolSU\Support\Completion\Contracts\CompletionCondition Class Reference
BristolSU\Support\Completion\Contracts\CompletionCondition Class Reference
Public Member Functions
__construct (string $moduleAlias)
moduleAlias ()
percentage ($settings, ActivityInstance $activityInstance, ModuleInstance $moduleInstance)
isComplete ($settings, ActivityInstance $activityInstance, ModuleInstance $moduleInstance)
options ()
name ()
description ()
alias ()
Private Attributes
$moduleAlias
Detailed Description
Completion Conditon class
Definition at line 11 of file CompletionCondition.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Completion\Contracts\CompletionCondition::__construct (string $moduleAlias)
Initialise the condition
Parameters
string $moduleAlias The module alias of the condition. This is passed in so that a condition can be made exclusive to a module, or can be a global condition which changes its behaviour depending on the module.
Definition at line 26 of file CompletionCondition.php.
References BristolSU\Support\Completion\Contracts\CompletionCondition\$moduleAlias, and BristolSU\Support\Completion\Contracts\CompletionCondition\moduleAlias().
Member Function Documentation
alias()
BristolSU\Support\Completion\Contracts\CompletionCondition::alias () abstract
The alias of the completion condition
Returns
string
Referenced by BristolSU\Support\Completion\Contracts\CompletionCondition\percentage(), and BristolSU\Support\Module\ModuleBuilder\setCompletionConditions().
description()
BristolSU\Support\Completion\Contracts\CompletionCondition::description () abstract
A description of the completion condition
Returns
string
Referenced by BristolSU\Support\Completion\Contracts\CompletionCondition\percentage(), and BristolSU\Support\Module\ModuleBuilder\setCompletionConditions().
isComplete()
BristolSU\Support\Completion\Contracts\CompletionCondition::isComplete ($settings, ActivityInstance $activityInstance, ModuleInstance $moduleInstance) abstract
Is the condition fully complete?
Parameters
array $settings Settings of the completion condition
ActivityInstance $activityInstance Activity instance to test
ModuleInstance $moduleInstance Module instance to test
Returns
bool If the condition is complete
Referenced by BristolSU\Support\Completion\Contracts\CompletionCondition\percentage().
moduleAlias()
BristolSU\Support\Completion\Contracts\CompletionCondition::moduleAlias ()
Get the module alias
Returns
string
Definition at line 36 of file CompletionCondition.php.
References BristolSU\Support\Completion\Contracts\CompletionCondition\$moduleAlias.
Referenced by BristolSU\Support\Completion\Contracts\CompletionCondition\__construct(), and BristolSU\Support\Completion\CompletionConditions\EventFired\EventFired\options().
name()
BristolSU\Support\Completion\Contracts\CompletionCondition::name () abstract
A name for the completion condition
Returns
string
Referenced by BristolSU\Support\Completion\Contracts\CompletionCondition\percentage(), and BristolSU\Support\Module\ModuleBuilder\setCompletionConditions().
options()
BristolSU\Support\Completion\Contracts\CompletionCondition::options () abstract
Options required by the completion condition.
This allows for you to get user input to modify the behaviour of this class. For example, you could give an option of a 'number of files' to be approved before the condition is complete. [ 'number_of_files' => 1 ] Any settings requested in here will be passed into the percentage or isComplete methods.
Returns
array
Referenced by BristolSU\Support\Completion\Contracts\CompletionCondition\percentage(), and BristolSU\Support\Module\ModuleBuilder\setCompletionConditions().
percentage()
BristolSU\Support\Completion\Contracts\CompletionCondition::percentage ($settings, ActivityInstance $activityInstance, ModuleInstance $moduleInstance)
Return the percentage completion of the module
By default, this function returns 0 if the condition is not complete, or 100 if the condition is complete. You may override this method to provide more granular percentage settings
Parameters
array $settings Settings of the completion condition
ActivityInstance $activityInstance The activity instance being tested
ModuleInstance $moduleInstance The module instance being tested
Returns
int Percentage complete.
Definition at line 52 of file CompletionCondition.php.
References BristolSU\Support\Completion\Contracts\CompletionCondition\alias(), BristolSU\Support\Completion\Contracts\CompletionCondition\description(), BristolSU\Support\Completion\Contracts\CompletionCondition\isComplete(), BristolSU\Support\Completion\Contracts\CompletionCondition\name(), and BristolSU\Support\Completion\Contracts\CompletionCondition\options().
Member Data Documentation
$moduleAlias
BristolSU\Support\Completion\Contracts\CompletionCondition::$moduleAlias private
Definition at line 18 of file CompletionCondition.php.
Referenced by BristolSU\Support\Completion\Contracts\CompletionCondition\__construct(), and BristolSU\Support\Completion\Contracts\CompletionCondition\moduleAlias().
The documentation for this class was generated from the following file:
src/Completion/Contracts/CompletionCondition.php