Bristol SU Support Package: BristolSU\Support\Permissions\PermissionStore Class Reference
BristolSU\Support\Permissions\PermissionStore Class Reference
Public Member Functions
registerSitePermission (string $ability, string $name, string $description)
registerPermission (Permission $permission)
registerModulePermission (string $ability, string $name, string $description, string $alias, bool $admin=false)
register (string $ability, string $name, string $description, string $alias, bool $admin=false)
get (string $ability)
all ()
Private Attributes
$permissions = []
Detailed Description
Definition at line 14 of file PermissionStore.php.
Member Function Documentation
all()
BristolSU\Support\Permissions\PermissionStore::all ()
Returns
array
Implements BristolSU\Support\Permissions\Contracts\PermissionStore.
Definition at line 94 of file PermissionStore.php.
References BristolSU\Support\Permissions\PermissionStore\$permissions.
get()
BristolSU\Support\Permissions\PermissionStore::get (string $ability)
Parameters
string $ability
Returns
Permission
Exceptions
Implements BristolSU\Support\Permissions\Contracts\PermissionStore.
Definition at line 83 of file PermissionStore.php.
register()
BristolSU\Support\Permissions\PermissionStore::register (string $ability, string $name, string $description, string $alias, bool $admin = false)
Parameters
string $ability
string $name
string $description
string $alias
bool $admin
Implements BristolSU\Support\Permissions\Contracts\PermissionStore.
Definition at line 73 of file PermissionStore.php.
References BristolSU\Support\Permissions\PermissionStore\registerModulePermission().
registerModulePermission()
BristolSU\Support\Permissions\PermissionStore::registerModulePermission (string $ability, string $name, string $description, string $alias, bool $admin = false)
Parameters
string $ability
string $name
string $description
string $alias
bool $admin
Implements BristolSU\Support\Permissions\Contracts\PermissionStore.
Definition at line 53 of file PermissionStore.php.
References BristolSU\Support\Permissions\PermissionStore\registerPermission().
Referenced by BristolSU\Support\Permissions\PermissionStore\register().
registerPermission()
BristolSU\Support\Permissions\PermissionStore::registerPermission (Permission $permission)
Parameters
Permission $permission
Implements BristolSU\Support\Permissions\Contracts\PermissionStore.
Definition at line 41 of file PermissionStore.php.
References BristolSU\Support\Permissions\Contracts\Models\Permission\getAbility().
Referenced by BristolSU\Support\Permissions\PermissionStore\registerModulePermission(), and BristolSU\Support\Permissions\PermissionStore\registerSitePermission().
registerSitePermission()
BristolSU\Support\Permissions\PermissionStore::registerSitePermission (string $ability, string $name, string $description)
Parameters
string $ability
string $name
string $description
Implements BristolSU\Support\Permissions\Contracts\PermissionStore.
Definition at line 27 of file PermissionStore.php.
References BristolSU\Support\Permissions\PermissionStore\registerPermission().
Member Data Documentation
$permissions
BristolSU\Support\Permissions\PermissionStore::$permissions = [] private
Definition at line 20 of file PermissionStore.php.
Referenced by BristolSU\Support\Permissions\PermissionStore\all().
The documentation for this class was generated from the following file:
src/Permissions/PermissionStore.php