Bristol SU Support Package: BristolSU\Support\Connection\ConnectorStore Class Reference
BristolSU\Support\Connection\ConnectorStore Class Reference
Public Member Functions
registerConnector (RegisteredConnector $connector)
register (string $name, string $description, string $alias, string $service, string $connector)
get (string $alias)
all ()
Private Attributes
$connectors = []
Detailed Description
Stores connectors
Definition at line 10 of file ConnectorStore.php.
Member Function Documentation
all()
BristolSU\Support\Connection\ConnectorStore::all ()
Return all registered connectors
Returns
RegisteredConnector[]
Implements BristolSU\Support\Connection\Contracts\ConnectorStore.
Definition at line 73 of file ConnectorStore.php.
References BristolSU\Support\Connection\ConnectorStore\$connectors.
get()
BristolSU\Support\Connection\ConnectorStore::get (string $alias)
Get a registered connector by alias
Parameters
string $alias Alias of the registered connector
Returns
RegisteredConnector
Exceptions
Implements BristolSU\Support\Connection\Contracts\ConnectorStore.
Definition at line 60 of file ConnectorStore.php.
register()
BristolSU\Support\Connection\ConnectorStore::register (string $name, string $description, string $alias, string $service, string $connector)
Register a new connector from its attributes
Parameters
string $name Name of the connector
string $description Description for the connector
string $alias Unique alias of the connector
string $service Alias of the service
string $connector Connector class name
Returns
void
Implements BristolSU\Support\Connection\Contracts\ConnectorStore.
Definition at line 42 of file ConnectorStore.php.
References BristolSU\Support\Connection\ConnectorStore\registerConnector().
registerConnector()
BristolSU\Support\Connection\ConnectorStore::registerConnector (RegisteredConnector $connector)
Register a connector class directly
Parameters
RegisteredConnector $connector Connector to register
Returns
void
Implements BristolSU\Support\Connection\Contracts\ConnectorStore.
Definition at line 26 of file ConnectorStore.php.
References BristolSU\Support\Connection\RegisteredConnector\getAlias().
Referenced by BristolSU\Support\Connection\ConnectorStore\register().
Member Data Documentation
$connectors
BristolSU\Support\Connection\ConnectorStore::$connectors = [] private
Definition at line 18 of file ConnectorStore.php.
Referenced by BristolSU\Support\Connection\ConnectorStore\all().
The documentation for this class was generated from the following file:
src/Connection/ConnectorStore.php