Bristol SU Support Package: BristolSU\Support\ActivityInstance\ActivityInstance Class Reference
BristolSU\Support\ActivityInstance\ActivityInstance Class Reference
Public Member Functions
getRunNumberAttribute ()
getParticipantAttribute ()
participant ()
moduleInstances ()
activity ()
getAuthIdentifierName ()
getAuthIdentifier ()
getAuthPassword ()
getRememberToken ()
setRememberToken ($value)
getRememberTokenName ()
Protected Attributes
$appends = ['run_number', 'participant']
$fillable
Detailed Description
An eloquent model representing an Activity Instance
Definition at line 19 of file ActivityInstance.php.
Member Function Documentation
activity()
BristolSU\Support\ActivityInstance\ActivityInstance::activity ()
Activity relationship
Returns
Definition at line 118 of file ActivityInstance.php.
Referenced by BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator\evaluateAdministrator(), BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator\evaluateParticipant(), BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateParticipant(), BristolSU\Support\ModuleInstance\Evaluator\ActivityInstanceEvaluator\evaluateResource(), BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateResource(), and BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\isComplete().
getAuthIdentifier()
BristolSU\Support\ActivityInstance\ActivityInstance::getAuthIdentifier ()
Get the unique identifier for the activity instance.
Returns
mixed
Definition at line 138 of file ActivityInstance.php.
getAuthIdentifierName()
BristolSU\Support\ActivityInstance\ActivityInstance::getAuthIdentifierName ()
Get the name of the unique identifier for the activity instance.
Returns
string
Definition at line 128 of file ActivityInstance.php.
getAuthPassword()
BristolSU\Support\ActivityInstance\ActivityInstance::getAuthPassword ()
Get the password for the activity instance.
Returns
string
Todo:
: Implement getAuthPassword() method.
Definition at line 148 of file ActivityInstance.php.
getParticipantAttribute()
BristolSU\Support\ActivityInstance\ActivityInstance::getParticipantAttribute ()
Get the model from the current resource as a Laravel attribute.
If the resource_type is user, returns the user with the id 'resource_id' If the resource_type is group, returns the group with the id 'resource_id' If the resource_type is role, returns the role with the id 'resource_id'
Returns
User|Group|Role The model for the resource of the activity instance.
Exceptions
Definition at line 77 of file ActivityInstance.php.
getRememberToken()
BristolSU\Support\ActivityInstance\ActivityInstance::getRememberToken ()
Get the token value for the "remember me" session.
Returns
string
Todo:
: Implement getRememberToken() method.
Definition at line 158 of file ActivityInstance.php.
getRememberTokenName()
BristolSU\Support\ActivityInstance\ActivityInstance::getRememberTokenName ()
Get the column name for the "remember me" token.
Returns
string
Todo:
: Implement getRememberTokenName() method.
Definition at line 179 of file ActivityInstance.php.
getRunNumberAttribute()
BristolSU\Support\ActivityInstance\ActivityInstance::getRunNumberAttribute ()
Get the run number of the activity instance as a Laravel attribute.
If there are multiple run throughs of an activity, this ID will number them from oldest to newest.
Returns
int
Definition at line 48 of file ActivityInstance.php.
moduleInstances()
BristolSU\Support\ActivityInstance\ActivityInstance::moduleInstances ()
Module Instance relationship
Returns
Definition at line 108 of file ActivityInstance.php.
participant()
BristolSU\Support\ActivityInstance\ActivityInstance::participant ()
Get the model from the current resource.
Function for retrieving the user, group or role associated with the activity instance.
Returns
User|Group|Role The model for the resource of the activity instance.
Definition at line 98 of file ActivityInstance.php.
Referenced by BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateResource().
setRememberToken()
BristolSU\Support\ActivityInstance\ActivityInstance::setRememberToken ($value)
Set the token value for the "remember me" session.
Parameters
string $value
Returns
void
Todo:
: Implement setRememberToken() method.
Definition at line 169 of file ActivityInstance.php.
Member Data Documentation
$appends
BristolSU\Support\ActivityInstance\ActivityInstance::$appends = ['run_number', 'participant'] protected
Definition at line 30 of file ActivityInstance.php.
$fillable
BristolSU\Support\ActivityInstance\ActivityInstance::$fillable protected
Initial value:
= [
        'name', 'description', 'activity_id', 'resource_type', 'resource_id'
    ]
Definition at line 37 of file ActivityInstance.php.
The documentation for this class was generated from the following file:
src/ActivityInstance/ActivityInstance.php