Bristol SU Support Package: BristolSU\Support\User\User Class Reference
BristolSU\Support\User\User Class Reference
Public Member Functions
controlId ()
controlUser ()
routeNotificationForMail ()
Protected Attributes
$fillable
$hidden
Detailed Description
Represents a user in the database
Definition at line 16 of file User.php.
Member Function Documentation
controlId()
BristolSU\Support\User\User::controlId ()
Get the ID of the control
Returns
int
Definition at line 43 of file User.php.
Referenced by BristolSU\Support\User\User\controlUser().
controlUser()
BristolSU\Support\User\User::controlUser ()
Get the control user attached to this database user
Returns
Definition at line 53 of file User.php.
References BristolSU\Support\User\User\controlId().
Referenced by BristolSU\Support\User\User\routeNotificationForMail().
routeNotificationForMail()
BristolSU\Support\User\User::routeNotificationForMail ()
Get the user email to send a notification to
Returns
string|null
Definition at line 63 of file User.php.
References BristolSU\Support\User\User\controlUser().
Member Data Documentation
$fillable
BristolSU\Support\User\User::$fillable protected
Initial value:
= [
        'control_id'
    ]
Definition at line 25 of file User.php.
$hidden
BristolSU\Support\User\User::$hidden protected
Initial value:
= [
        'password', 'remember_token'
    ]
Definition at line 34 of file User.php.
The documentation for this class was generated from the following file:
src/User/User.php