Bristol SU Support Package: BristolSU\Support\DataPlatform\Models\Model Class Reference
BristolSU\Support\DataPlatform\Models\Model Class Reference
Public Member Functions
__construct ($attributes=[])
__get ($name)
toArray ()
toJson ($options=0)
__toString ()
Protected Attributes
$attributes
Detailed Description
Definition at line 14 of file Model.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\DataPlatform\Models\Model::__construct ($attributes = [])
Model constructor.
Parameters
array $attributes
Definition at line 25 of file Model.php.
References BristolSU\Support\DataPlatform\Models\Model\$attributes.
Member Function Documentation
__get()
BristolSU\Support\DataPlatform\Models\Model::__get ($name)
Parameters
$name
Returns
mixed|null
Definition at line 34 of file Model.php.
__toString()
BristolSU\Support\DataPlatform\Models\Model::__toString ()
Definition at line 59 of file Model.php.
References BristolSU\Support\DataPlatform\Models\Model\toJson().
toArray()
BristolSU\Support\DataPlatform\Models\Model::toArray ()
Definition at line 46 of file Model.php.
References BristolSU\Support\DataPlatform\Models\Model\$attributes.
Referenced by BristolSU\Support\DataPlatform\Models\Model\toJson().
toJson()
BristolSU\Support\DataPlatform\Models\Model::toJson ($options = 0)
Definition at line 54 of file Model.php.
References BristolSU\Support\DataPlatform\Models\Model\toArray().
Referenced by BristolSU\Support\DataPlatform\Models\Model\__toString().
Member Data Documentation
$attributes
BristolSU\Support\DataPlatform\Models\Model::$attributes protected
Definition at line 19 of file Model.php.
Referenced by BristolSU\Support\DataPlatform\Models\Model\__construct(), and BristolSU\Support\DataPlatform\Models\Model\toArray().
The documentation for this class was generated from the following file:
src/DataPlatform/Models/Model.php