Bristol SU Support Package: BristolSU\Support\Connection\Client\CachedClientDecorator Class Reference
BristolSU\Support\Connection\Client\CachedClientDecorator Class Reference
Public Member Functions
__construct (Client $client, Cache $cache)
request ($method, $uri, array $options=[])
Private Member Functions
getKey ($method, $uri, $options)
isCacheable ($method)
forwardCall ($method, $uri, $options)
Private Attributes
$client
$cache
Detailed Description
Cache decorator to cache requests
Definition at line 12 of file CachedClientDecorator.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Connection\Client\CachedClientDecorator::__construct (Client $client, Cache $cache)
Parameters
Client $client Client to forward calls onto
Cache $cache Cache repository to store requests in
Definition at line 32 of file CachedClientDecorator.php.
References BristolSU\Support\Connection\Client\CachedClientDecorator\$cache, and BristolSU\Support\Connection\Client\CachedClientDecorator\$client.
Member Function Documentation
forwardCall()
BristolSU\Support\Connection\Client\CachedClientDecorator::forwardCall ($method, $uri, $options) private
Forward the call onto the underlying client instance
Parameters
string $method Method of the request
string $uri URL for the request
array $options Guzzle options for the request
Returns
ResponseInterface
Definition at line 92 of file CachedClientDecorator.php.
Referenced by BristolSU\Support\Connection\Client\CachedClientDecorator\request().
getKey()
BristolSU\Support\Connection\Client\CachedClientDecorator::getKey ($method, $uri, $options) private
Get a unique key for the request
Parameters
string $method Method for the request
string $uri URL for the request
array $options Options for the request
Returns
string A key unique to the request
Definition at line 66 of file CachedClientDecorator.php.
Referenced by BristolSU\Support\Connection\Client\CachedClientDecorator\request().
isCacheable()
BristolSU\Support\Connection\Client\CachedClientDecorator::isCacheable ($method) private
Is the request cacheable?
Parameters
string $method Method of the request
Returns
bool Can the request be cached?
Definition at line 77 of file CachedClientDecorator.php.
Referenced by BristolSU\Support\Connection\Client\CachedClientDecorator\request().
request()
BristolSU\Support\Connection\Client\CachedClientDecorator::request ($method, $uri, array $options = [])
Cache a request if cacheable, and return the request response
Parameters
string $method Request method to use
string $uri URL to make the request too
array $options Options as specified in Guzzle
Returns
ResponseInterface
Implements BristolSU\Support\Connection\Contracts\Client\Client.
Definition at line 47 of file CachedClientDecorator.php.
References BristolSU\Support\Connection\Client\CachedClientDecorator\forwardCall(), BristolSU\Support\Connection\Client\CachedClientDecorator\getKey(), and BristolSU\Support\Connection\Client\CachedClientDecorator\isCacheable().
Member Data Documentation
$cache
BristolSU\Support\Connection\Client\CachedClientDecorator::$cache private
Definition at line 26 of file CachedClientDecorator.php.
Referenced by BristolSU\Support\Connection\Client\CachedClientDecorator\__construct().
$client
BristolSU\Support\Connection\Client\CachedClientDecorator::$client private
Definition at line 19 of file CachedClientDecorator.php.
Referenced by BristolSU\Support\Connection\Client\CachedClientDecorator\__construct().
The documentation for this class was generated from the following file:
src/Connection/Client/CachedClientDecorator.php