Bristol SU Support Package: BristolSU\Support\Connection\Contracts\Connector Class Reference
BristolSU\Support\Connection\Contracts\Connector Class Reference
Public Member Functions
__construct (Client $client)
request ($method, $uri, array $options=[])
test ()
setSettings (array $settings=[])
getSetting (string $key, $default=null)
Static Public Member Functions
static settingsSchema ()
Protected Attributes
$client
$settings
Detailed Description
Definition at line 9 of file Connector.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Connection\Contracts\Connector::__construct (Client $client)
Definition at line 22 of file Connector.php.
References BristolSU\Support\Connection\Contracts\Connector\$client, BristolSU\Support\Connection\Contracts\Connector\request(), BristolSU\Support\Connection\Contracts\Connector\settingsSchema(), and BristolSU\Support\Connection\Contracts\Connector\test().
Member Function Documentation
getSetting()
BristolSU\Support\Connection\Contracts\Connector::getSetting (string $key, $default = null)
Get a setting value
Parameters
string $key
null $default
Returns
mixed
Exceptions
Definition at line 71 of file Connector.php.
References function\settings().
request()
BristolSU\Support\Connection\Contracts\Connector::request ($method, $uri, array $options = []) abstract
Prepare and send a request.
You may add authentication, default fields or anything else here. Call $this->client->request and return the result when prepared.
Parameters
$method
$uri
array $options
Returns
mixed
Referenced by BristolSU\Support\Connection\Contracts\Connector\__construct().
setSettings()
BristolSU\Support\Connection\Contracts\Connector::setSettings (array $settings = [])
Set the settings on the connector
Parameters
array $settings
Definition at line 59 of file Connector.php.
References BristolSU\Support\Connection\Contracts\Connector\$settings, and function\settings().
Referenced by BristolSU\Support\Connection\ConnectorFactory\createFromConnection().
settingsSchema()
static BristolSU\Support\Connection\Contracts\Connector::settingsSchema () static abstract
Get the settings schema to use
Returns
Form
Referenced by BristolSU\Support\Connection\Contracts\Connector\__construct().
test()
BristolSU\Support\Connection\Contracts\Connector::test () abstract
Check the connection is still connected
Returns
bool
Referenced by BristolSU\Support\Connection\Contracts\Connector\__construct().
Member Data Documentation
$client
BristolSU\Support\Connection\Contracts\Connector::$client protected
Definition at line 15 of file Connector.php.
Referenced by BristolSU\Support\Connection\Contracts\Connector\__construct().
$settings
BristolSU\Support\Connection\Contracts\Connector::$settings protected
Definition at line 20 of file Connector.php.
Referenced by BristolSU\Support\Connection\Contracts\Connector\setSettings().
The documentation for this class was generated from the following file:
src/Connection/Contracts/Connector.php