Bristol SU Support Package: BristolSU\Support\Filters\Commands\CacheFilters Class Reference
BristolSU\Support\Filters\Commands\CacheFilters Class Reference
Public Member Functions
handle (FilterInstanceRepository $filterInstanceRepository, UserRepository $userRepository, GroupRepository $groupRepository, RoleRepository $roleRepository)
Protected Attributes
$signature = 'filters:cache'
$description = 'Caches all filter results for increased speed in page load'
Private Member Functions
cacheFilter (FilterInstance $filterInstance, Collection $models)
Detailed Description
Command to cache the result of all filters
Definition at line 17 of file CacheFilters.php.
Member Function Documentation
cacheFilter()
BristolSU\Support\Filters\Commands\CacheFilters::cacheFilter (FilterInstance $filterInstance, Collection $models) private
Fire a job to cache the given filter with the given models
Parameters
FilterInstance $filterInstance Filter instance to cache
Collection $models Models to cache the result of.
Definition at line 78 of file CacheFilters.php.
Referenced by BristolSU\Support\Filters\Commands\CacheFilters\handle().
handle()
BristolSU\Support\Filters\Commands\CacheFilters::handle (FilterInstanceRepository $filterInstanceRepository, UserRepository $userRepository, GroupRepository $groupRepository, RoleRepository $roleRepository)
Cache the result of all filter instances.
This function will fire a job to cache the filter of all filter instances.
Parameters
FilterInstanceRepository $filterInstanceRepository Filter instance repository to get the filter instances from
UserRepository $userRepository Repository to get all users from
GroupRepository $groupRepository Repository to get all groups from
RoleRepository $roleRepository Repository to get all roles from
Definition at line 44 of file CacheFilters.php.
References BristolSU\Support\Filters\Contracts\FilterInstanceRepository\all(), and BristolSU\Support\Filters\Commands\CacheFilters\cacheFilter().
Member Data Documentation
$description
BristolSU\Support\Filters\Commands\CacheFilters::$description = 'Caches all filter results for increased speed in page load' protected
Definition at line 32 of file CacheFilters.php.
$signature
BristolSU\Support\Filters\Commands\CacheFilters::$signature = 'filters:cache' protected
Definition at line 25 of file CacheFilters.php.
The documentation for this class was generated from the following file:
src/Filters/Commands/CacheFilters.php