Bristol SU Support Package: BristolSU\Support\Connection\ServiceRequest Class Reference
BristolSU\Support\Connection\ServiceRequest Class Reference
Public Member Functions
required (string $alias, array $services=[])
optional (string $alias, array $services=[])
getRequired (string $alias)
getOptional (string $alias)
getAllRequired ()
getAllOptional ()
Private Attributes
$required = []
$optional = []
Detailed Description
Tool for requesting services for a module
Definition at line 10 of file ServiceRequest.php.
Member Function Documentation
getAllOptional()
BristolSU\Support\Connection\ServiceRequest::getAllOptional ()
Get all optional services from all modules
Returns
array ['module_alias' => ['typeform', 'facebook', ...], ...]
Implements BristolSU\Support\Connection\Contracts\ServiceRequest.
Definition at line 100 of file ServiceRequest.php.
References BristolSU\Support\Connection\ServiceRequest\$optional.
getAllRequired()
BristolSU\Support\Connection\ServiceRequest::getAllRequired ()
Get all required services from all modules
Returns
array ['module_alias' => ['typeform', 'facebook', ...], ...]
Implements BristolSU\Support\Connection\Contracts\ServiceRequest.
Definition at line 90 of file ServiceRequest.php.
References BristolSU\Support\Connection\ServiceRequest\$required.
getOptional()
BristolSU\Support\Connection\ServiceRequest::getOptional (string $alias)
Get all optional services for a module
Parameters
string $alias Alias of the module
Returns
array Array of optional services e.g. ['typeform', 'facebook']
Implements BristolSU\Support\Connection\Contracts\ServiceRequest.
Definition at line 77 of file ServiceRequest.php.
References BristolSU\Support\Connection\ServiceRequest\optional().
getRequired()
BristolSU\Support\Connection\ServiceRequest::getRequired (string $alias)
Get all required services for a module
Parameters
string $alias Alias of the module
Returns
array Array of services required e.g. ['typeform', 'facebook']
Implements BristolSU\Support\Connection\Contracts\ServiceRequest.
Definition at line 63 of file ServiceRequest.php.
References BristolSU\Support\Connection\ServiceRequest\required().
optional()
BristolSU\Support\Connection\ServiceRequest::optional (string $alias, array $services = [])
Request an optional service.
Parameters
string $alias Alias of the module requesting the service
array $services An array of services that are optional but useable
Returns
void
Implements BristolSU\Support\Connection\Contracts\ServiceRequest.
Definition at line 52 of file ServiceRequest.php.
Referenced by BristolSU\Support\Connection\ServiceRequest\getOptional().
required()
BristolSU\Support\Connection\ServiceRequest::required (string $alias, array $services = [])
Request a required service.
Parameters
string $alias Alias of the module requesting the service
array $services An array of services that are required
Returns
void
Implements BristolSU\Support\Connection\Contracts\ServiceRequest.
Definition at line 40 of file ServiceRequest.php.
Referenced by BristolSU\Support\Connection\ServiceRequest\getRequired().
Member Data Documentation
$optional
BristolSU\Support\Connection\ServiceRequest::$optional = [] private
Definition at line 31 of file ServiceRequest.php.
Referenced by BristolSU\Support\Connection\ServiceRequest\getAllOptional().
$required
BristolSU\Support\Connection\ServiceRequest::$required = [] private
Definition at line 21 of file ServiceRequest.php.
Referenced by BristolSU\Support\Connection\ServiceRequest\getAllRequired().
The documentation for this class was generated from the following file:
src/Connection/ServiceRequest.php