Bristol SU Support Package: BristolSU\Support\Filters\Contracts\Filters\UserFilter Class Reference
BristolSU\Support\Filters\Contracts\Filters\UserFilter Class Reference
Public Member Functions
setModel ($model)
hasModel ()
model ()
user ()
Public Member Functions inherited from BristolSU\Support\Filters\Contracts\Filters\Filter
model ()
options ()
hasModel ()
setModel ($model)
evaluate ($settings)
name ()
description ()
alias ()
toArray ()
Private Attributes
$user
Detailed Description
A filter for a user
Definition at line 11 of file UserFilter.php.
Member Function Documentation
hasModel()
BristolSU\Support\Filters\Contracts\Filters\UserFilter::hasModel ()
Does the filter have a user?
Returns
bool If the filter has a user
Definition at line 44 of file UserFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\UserFilter\user().
model()
BristolSU\Support\Filters\Contracts\Filters\UserFilter::model ()
Get the user
Returns
User|null
Definition at line 54 of file UserFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\UserFilter\$user.
Referenced by BristolSU\Support\Filters\Contracts\Filters\UserFilter\user().
setModel()
BristolSU\Support\Filters\Contracts\Filters\UserFilter::setModel ($model)
Set the user
Parameters
User $model User to set
Returns
void
Exceptions
Definition at line 29 of file UserFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\UserFilter\user().
user()
BristolSU\Support\Filters\Contracts\Filters\UserFilter::user ()
Get the user
Returns
User|null
Definition at line 64 of file UserFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\UserFilter\model().
Referenced by BristolSU\Support\Filters\Filters\User\UserEmailIs\evaluate(), BristolSU\Support\Filters\Contracts\Filters\UserFilter\hasModel(), and BristolSU\Support\Filters\Contracts\Filters\UserFilter\setModel().
Member Data Documentation
$user
BristolSU\Support\Filters\Contracts\Filters\UserFilter::$user private
Definition at line 19 of file UserFilter.php.
Referenced by BristolSU\Support\Filters\Filters\User\UserEmailIs\evaluate(), and BristolSU\Support\Filters\Contracts\Filters\UserFilter\model().
The documentation for this class was generated from the following file:
src/Filters/Contracts/Filters/UserFilter.php