Bristol SU Support Package: BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator Class Reference
BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator Class Reference
Public Member Functions
__construct (EvaluationContract $evaluation)
evaluateAdministrator (ActivityInstance $activityInstance, ModuleInstance $moduleInstance, ?User $user=null, ?Group $group=null, ?Role $role=null)
evaluateParticipant (ActivityInstance $activityInstance, ModuleInstance $moduleInstance, ?User $user=null, ?Group $group=null, ?Role $role=null)
evaluateResource (ActivityInstance $activityInstance, ModuleInstance $moduleInstance)
Private Member Functions
isComplete (ActivityInstance $activityInstance, ModuleInstance $moduleInstance)
Private Attributes
$evaluation
Detailed Description
Definition at line 26 of file ModuleInstanceEvaluator.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator::__construct (EvaluationContract $evaluation)
ModuleInstanceEvaluator constructor.
Parameters
EvaluationContract $evaluation
Authentication $authentication
Definition at line 39 of file ModuleInstanceEvaluator.php.
References BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\$evaluation.
Member Function Documentation
evaluateAdministrator()
BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator::evaluateAdministrator (ActivityInstance $activityInstance, ModuleInstance $moduleInstance, ?User $user = null, ?Group $group = null, ?Role $role = null)
Parameters
ModuleInstance $moduleInstance
Returns
EvaluationContract|mixed
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\ModuleInstanceEvaluator.
Definition at line 48 of file ModuleInstanceEvaluator.php.
References BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\$evaluation.
evaluateParticipant()
BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator::evaluateParticipant (ActivityInstance $activityInstance, ModuleInstance $moduleInstance, ?User $user = null, ?Group $group = null, ?Role $role = null)
Parameters
ModuleInstance $moduleInstance
Returns
EvaluationContract|mixed
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\ModuleInstanceEvaluator.
Definition at line 62 of file ModuleInstanceEvaluator.php.
References BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\$evaluation, BristolSU\Support\ActivityInstance\ActivityInstance\activity(), and BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\isComplete().
evaluateResource()
BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator::evaluateResource (ActivityInstance $activityInstance, ModuleInstance $moduleInstance)
Implements BristolSU\Support\ModuleInstance\Contracts\Evaluator\ModuleInstanceEvaluator.
Definition at line 81 of file ModuleInstanceEvaluator.php.
References BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\$evaluation, BristolSU\Support\ActivityInstance\ActivityInstance\activity(), BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\isComplete(), and BristolSU\Support\ActivityInstance\ActivityInstance\participant().
isComplete()
BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator::isComplete (ActivityInstance $activityInstance, ModuleInstance $moduleInstance) private
Todo:
make active and visible meaningful
Definition at line 74 of file ModuleInstanceEvaluator.php.
References BristolSU\Support\ActivityInstance\ActivityInstance\activity().
Referenced by BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateParticipant(), and BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateResource().
Member Data Documentation
$evaluation
BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator::$evaluation private
Definition at line 32 of file ModuleInstanceEvaluator.php.
Referenced by BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\__construct(), BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateAdministrator(), BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateParticipant(), and BristolSU\Support\ModuleInstance\Evaluator\ModuleInstanceEvaluator\evaluateResource().
The documentation for this class was generated from the following file:
src/ModuleInstance/Evaluator/ModuleInstanceEvaluator.php