Bristol SU Support Package: BristolSU\Support\Filters\Contracts\Filters\RoleFilter Class Reference
BristolSU\Support\Filters\Contracts\Filters\RoleFilter Class Reference
Public Member Functions
setModel ($model)
hasModel ()
model ()
role ()
Public Member Functions inherited from BristolSU\Support\Filters\Contracts\Filters\Filter
model ()
options ()
hasModel ()
setModel ($model)
evaluate ($settings)
name ()
description ()
alias ()
toArray ()
Private Attributes
$role
Detailed Description
A filter for a role
Definition at line 11 of file RoleFilter.php.
Member Function Documentation
hasModel()
BristolSU\Support\Filters\Contracts\Filters\RoleFilter::hasModel ()
Does the filter have a role?
Returns
bool If the filter has a role
Definition at line 44 of file RoleFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\RoleFilter\role().
model()
BristolSU\Support\Filters\Contracts\Filters\RoleFilter::model ()
Get the role
Returns
Role|null
Definition at line 54 of file RoleFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\RoleFilter\$role.
Referenced by BristolSU\Support\Filters\Contracts\Filters\RoleFilter\role().
role()
BristolSU\Support\Filters\Contracts\Filters\RoleFilter::role ()
Get the role
Returns
Role|null
Definition at line 64 of file RoleFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\RoleFilter\model().
Referenced by BristolSU\Support\Filters\Filters\Role\RoleHasPosition\evaluate(), BristolSU\Support\Filters\Filters\Role\RoleTagged\evaluate(), BristolSU\Support\Filters\Contracts\Filters\RoleFilter\hasModel(), and BristolSU\Support\Filters\Contracts\Filters\RoleFilter\setModel().
setModel()
BristolSU\Support\Filters\Contracts\Filters\RoleFilter::setModel ($model)
Set the role
Parameters
Role $model Role to set
Returns
void
Exceptions
Definition at line 29 of file RoleFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\RoleFilter\role().
Member Data Documentation
$role
BristolSU\Support\Filters\Contracts\Filters\RoleFilter::$role private
Definition at line 19 of file RoleFilter.php.
Referenced by BristolSU\Support\Filters\Contracts\Filters\RoleFilter\model().
The documentation for this class was generated from the following file:
src/Filters/Contracts/Filters/RoleFilter.php