Bristol SU Support Package: BristolSU\Support\Filters\Contracts\Filters\GroupFilter Class Reference
BristolSU\Support\Filters\Contracts\Filters\GroupFilter Class Reference
Public Member Functions
setModel ($model)
hasModel ()
model ()
group ()
Public Member Functions inherited from BristolSU\Support\Filters\Contracts\Filters\Filter
model ()
options ()
hasModel ()
setModel ($model)
evaluate ($settings)
name ()
description ()
alias ()
toArray ()
Private Attributes
$group
Detailed Description
A filter for a group
Definition at line 11 of file GroupFilter.php.
Member Function Documentation
group()
BristolSU\Support\Filters\Contracts\Filters\GroupFilter::group ()
Get the group
Returns
Group|null
Definition at line 64 of file GroupFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\GroupFilter\model().
Referenced by BristolSU\Support\Filters\Filters\Group\GroupNameIs\evaluate(), BristolSU\Support\Filters\Filters\Group\GroupTagged\evaluate(), BristolSU\Support\Filters\Contracts\Filters\GroupFilter\hasModel(), and BristolSU\Support\Filters\Contracts\Filters\GroupFilter\setModel().
hasModel()
BristolSU\Support\Filters\Contracts\Filters\GroupFilter::hasModel ()
Does the filter have a group?
Returns
bool If the filter has a group
Definition at line 44 of file GroupFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\GroupFilter\group().
model()
BristolSU\Support\Filters\Contracts\Filters\GroupFilter::model ()
Get the group
Returns
Group|null
Definition at line 54 of file GroupFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\GroupFilter\$group.
Referenced by BristolSU\Support\Filters\Contracts\Filters\GroupFilter\group().
setModel()
BristolSU\Support\Filters\Contracts\Filters\GroupFilter::setModel ($model)
Set the group
Parameters
Group $model Group to set
Returns
void
Exceptions
Definition at line 29 of file GroupFilter.php.
References BristolSU\Support\Filters\Contracts\Filters\GroupFilter\group().
Member Data Documentation
$group
BristolSU\Support\Filters\Contracts\Filters\GroupFilter::$group private
Definition at line 19 of file GroupFilter.php.
Referenced by BristolSU\Support\Filters\Contracts\Filters\GroupFilter\model().
The documentation for this class was generated from the following file:
src/Filters/Contracts/Filters/GroupFilter.php