Bristol SU Support Package: BristolSU\Support\Action\Actions\Log Class Reference
BristolSU\Support\Action\Actions\Log Class Reference
Public Member Functions
run ()
Public Member Functions inherited from BristolSU\Support\Action\Contracts\Action
__construct (array $data=[])
handle ()
getResponse ()
option (string $key, $default=null)
getData ()
run ()
Public Member Functions inherited from BristolSU\Support\Action\History\RecordsHistory
setActionInstanceId (int $actionInstanceId)
setEventFields (array $eventFields)
setSettings (array $settings)
saveHistory (ActionResponse $response)
Static Public Member Functions
static options ()
Static Public Member Functions inherited from BristolSU\Support\Action\Contracts\Action
static options ()
Detailed Description
Logging Action.
Logs a message to the PHP log.
Definition at line 15 of file Log.php.
Member Function Documentation
options()
static BristolSU\Support\Action\Actions\Log::options () static
Definition at line 34 of file Log.php.
run()
BristolSU\Support\Action\Actions\Log::run ()
Handle logging the message to the log
Definition at line 21 of file Log.php.
References BristolSU\Support\Action\ActionResponse\failure(), BristolSU\Support\Action\Contracts\Action\option(), and BristolSU\Support\Action\ActionResponse\success().
The documentation for this class was generated from the following file:
src/Action/Actions/Log.php