Bristol SU Support Package: BristolSU\Support\Permissions\Contracts\Models\Permission Interface Reference
BristolSU\Support\Permissions\Contracts\Models\Permission Interface Reference
Public Member Functions
__construct (string $ability='', string $name='', string $description='')
setAbility (string $ability)
setName (string $name)
setDescription (string $description)
setType (string $type)
setModuleAlias (?string $moduleAlias)
setModuleType (?string $moduleType)
getAbility ()
getName ()
getDescription ()
getType ()
getModuleAlias ()
getModuleType ()
Detailed Description
Represents a permission registered in a Service Provider
Definition at line 11 of file Permission.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Support\Permissions\Contracts\Models\Permission::__construct (string $ability = '', string $name = '', string $description = '')
Parameters
string $ability Ability string for the permission
string $name A name for the permission
string $description A description for the permission
Member Function Documentation
getAbility()
BristolSU\Support\Permissions\Contracts\Models\Permission::getAbility ()
Get the ability string for the permission
Returns
string Ability string
Implemented in BristolSU\Support\Permissions\Models\Permission.
Referenced by BristolSU\Support\Permissions\Testers\ModuleInstanceGroupOverridePermission\can(), BristolSU\Support\Permissions\Testers\ModuleInstanceRoleOverridePermission\can(), BristolSU\Support\Permissions\Testers\ModuleInstanceUserOverridePermission\can(), BristolSU\Support\Permissions\Testers\SystemUserPermission\can(), BristolSU\Support\Permissions\Testers\ModuleInstancePermissions\can(), and BristolSU\Support\Permissions\PermissionStore\registerPermission().
getDescription()
BristolSU\Support\Permissions\Contracts\Models\Permission::getDescription ()
Get the description of the permission
Returns
string Description of the permission
Implemented in BristolSU\Support\Permissions\Models\Permission.
getModuleAlias()
BristolSU\Support\Permissions\Contracts\Models\Permission::getModuleAlias ()
Get the alias of the module for which the permission belongs
Returns
string|null Alias of the module. Null if not a module permission
Implemented in BristolSU\Support\Permissions\Models\Permission.
Referenced by BristolSU\Support\Permissions\PermissionRepository\forModule().
getModuleType()
BristolSU\Support\Permissions\Contracts\Models\Permission::getModuleType ()
Get the type of module permission.
If the permission is an admin permission, this function should return 'administrator'. Otherwise, the function will return 'participant'.
Returns
string|null. administrator/participant. Null if not a module permission
Implemented in BristolSU\Support\Permissions\Models\Permission.
getName()
BristolSU\Support\Permissions\Contracts\Models\Permission::getName ()
Get the name of the permission
Returns
string Name of the permission
Implemented in BristolSU\Support\Permissions\Models\Permission.
getType()
BristolSU\Support\Permissions\Contracts\Models\Permission::getType ()
Get the type of the permission
Returns
string Type of the permission
Implemented in BristolSU\Support\Permissions\Models\Permission.
Referenced by BristolSU\Support\Permissions\Testers\ModuleInstanceUserOverridePermission\can(), and BristolSU\Support\Permissions\Testers\SystemUserPermission\can().
setAbility()
BristolSU\Support\Permissions\Contracts\Models\Permission::setAbility (string $ability)
Set the ability string of the permission
Parameters
string $ability Ability String
Returns
void
Implemented in BristolSU\Support\Permissions\Models\Permission.
setDescription()
BristolSU\Support\Permissions\Contracts\Models\Permission::setDescription (string $description)
Set the description of the permission
Parameters
string $description Description of the permission
Returns
void
Implemented in BristolSU\Support\Permissions\Models\Permission.
setModuleAlias()
BristolSU\Support\Permissions\Contracts\Models\Permission::setModuleAlias (?string $moduleAlias)
Set the module alias for the permission
If the permission is a module permission, the module alias is the module which has registered the permission
Parameters
null | string $moduleAlias Module that registers the permission
Returns
void
Implemented in BristolSU\Support\Permissions\Models\Permission.
setModuleType()
BristolSU\Support\Permissions\Contracts\Models\Permission::setModuleType (?string $moduleType)
Set the module type.
If the permission is a module permission, this should either be 'administrator' or 'participant', depending on if the module is an admin or a participant permission.
Parameters
null | string $moduleType
Returns
mixed
Implemented in BristolSU\Support\Permissions\Models\Permission.
setName()
BristolSU\Support\Permissions\Contracts\Models\Permission::setName (string $name)
Set the name of the permission
Parameters
string $name Name of the permission
Returns
void
Implemented in BristolSU\Support\Permissions\Models\Permission.
setType()
BristolSU\Support\Permissions\Contracts\Models\Permission::setType (string $type)
Set the type of permission.
The type of the permission can either be 'global' for a system permission, or 'module' for a module permission
Parameters
string $type Type of the permission, either global or module
Returns
void
Implemented in BristolSU\Support\Permissions\Models\Permission.
The documentation for this interface was generated from the following file:
src/Permissions/Contracts/Models/Permission.php