Bristol SU Support Package: BristolSU\Support\Module\Contracts\Module Interface Reference
BristolSU\Support\Module\Contracts\Module Interface Reference
Public Member Functions
setAlias (string $alias)
getAlias ()
setName (string $name)
getName ()
setCompletionConditions (array $completionConditions)
getCompletionConditions ()
setDescription (string $description)
getDescription ()
setPermissions (array $permissions)
getPermissions ()
setSettings (array $settings)
getSettings ()
setTriggers (array $triggers)
getTriggers ()
setServices (array $services)
getServices ()
Detailed Description
Definition at line 12 of file Module.php.
Member Function Documentation
getAlias()
BristolSU\Support\Module\Contracts\Module::getAlias ()
Returns
string
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
getCompletionConditions()
BristolSU\Support\Module\Contracts\Module::getCompletionConditions ()
Returns
string
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
getDescription()
BristolSU\Support\Module\Contracts\Module::getDescription ()
Returns
string
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
getName()
BristolSU\Support\Module\Contracts\Module::getName ()
Returns
string
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
getPermissions()
BristolSU\Support\Module\Contracts\Module::getPermissions ()
Returns
array
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
getServices()
BristolSU\Support\Module\Contracts\Module::getServices ()
Returns
array
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
getSettings()
BristolSU\Support\Module\Contracts\Module::getSettings ()
Returns
array
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
getTriggers()
BristolSU\Support\Module\Contracts\Module::getTriggers ()
Returns
array
Implemented in BristolSU\Support\Module\Module.
Referenced by BristolSU\Support\Module\Module\toArray().
setAlias()
BristolSU\Support\Module\Contracts\Module::setAlias (string $alias)
Parameters
string $alias
Implemented in BristolSU\Support\Module\Module.
setCompletionConditions()
BristolSU\Support\Module\Contracts\Module::setCompletionConditions (array $completionConditions)
Parameters
string $completionConditions
Implemented in BristolSU\Support\Module\Module.
setDescription()
BristolSU\Support\Module\Contracts\Module::setDescription (string $description)
Parameters
string $description
Implemented in BristolSU\Support\Module\Module.
setName()
BristolSU\Support\Module\Contracts\Module::setName (string $name)
Parameters
string $name
Implemented in BristolSU\Support\Module\Module.
setPermissions()
BristolSU\Support\Module\Contracts\Module::setPermissions (array $permissions)
Parameters
array $permissions
Implemented in BristolSU\Support\Module\Module.
setServices()
BristolSU\Support\Module\Contracts\Module::setServices (array $services)
Parameters
array $services
Implemented in BristolSU\Support\Module\Module.
setSettings()
BristolSU\Support\Module\Contracts\Module::setSettings (array $settings)
Parameters
array $settings
Implemented in BristolSU\Support\Module\Module.
setTriggers()
BristolSU\Support\Module\Contracts\Module::setTriggers (array $triggers)
Parameters
array $triggers
Implemented in BristolSU\Support\Module\Module.
The documentation for this interface was generated from the following file:
src/Module/Contracts/Module.php