Bristol SU Support Package: BristolSU\Support\Filters\Contracts\FilterInstance Interface Reference
BristolSU\Support\Filters\Contracts\FilterInstance Interface Reference
Public Member Functions
name ()
alias ()
settings ()
for ()
Detailed Description
Definition at line 11 of file FilterInstance.php.
Member Function Documentation
alias()
BristolSU\Support\Filters\Contracts\FilterInstance::alias ()
Implemented in BristolSU\Support\Filters\FilterInstance.
Referenced by BristolSU\Support\Filters\FilterTester\evaluate(), and BristolSU\Support\Filters\FilterInstance\for().
for()
BristolSU\Support\Filters\Contracts\FilterInstance::for ()
Implemented in BristolSU\Support\Filters\FilterInstance.
name()
BristolSU\Support\Filters\Contracts\FilterInstance::name ()
Implemented in BristolSU\Support\Filters\FilterInstance.
settings()
BristolSU\Support\Filters\Contracts\FilterInstance::settings ()
Implemented in BristolSU\Support\Filters\FilterInstance.
Referenced by BristolSU\Support\Filters\FilterTester\evaluate().
The documentation for this interface was generated from the following file:
src/Filters/Contracts/FilterInstance.php