Bristol SU Support Package: BristolSU\Support\Module\Contracts\ModuleManager Interface Reference
BristolSU\Support\Module\Contracts\ModuleManager Interface Reference
Public Member Functions
register ($alias)
aliases ()
exists (string $alias)
Detailed Description
Manages module registration
Definition at line 8 of file ModuleManager.php.
Member Function Documentation
aliases()
BristolSU\Support\Module\Contracts\ModuleManager::aliases ()
Get all aliases which have been registered
Returns
array Array of module aliases
Implemented in BristolSU\Support\Module\ModuleManager.
Referenced by BristolSU\Support\Module\ModuleManager\exists(), and BristolSU\Support\Module\ModuleManager\register().
exists()
BristolSU\Support\Module\Contracts\ModuleManager::exists (string $alias)
Has the given module alias been registered?
Parameters
string $alias Alias to test
Returns
bool If the module has been registered
Implemented in BristolSU\Support\Module\ModuleManager.
Referenced by BristolSU\Support\Module\ModuleManager\register().
register()
BristolSU\Support\Module\Contracts\ModuleManager::register ($alias)
Register a new module
Parameters
string $alias Alias of the module
Returns
void
Implemented in BristolSU\Support\Module\ModuleManager.
The documentation for this interface was generated from the following file:
src/Module/Contracts/ModuleManager.php