Bristol SU Support Package: function Namespace Reference
function Namespace Reference
Functions
baseDirectory ()
alias ()
settings ()
registerSettings ()
registerGlobalScript (string $path)
Detailed Description
Base namespace of the controllers.
Routes will use this namespace to prevent you from having to give the fully qualified name of the controller in the routes file. Will look something like
Returns
string
Function Documentation
alias()
function\alias () abstract
Return the alias of the module
Returns
string Module alias
Referenced by BristolSU\Support\Testing\CreatesModuleEnvironment\adminApiUrl(), BristolSU\Support\Testing\CreatesModuleEnvironment\adminUrl(), BristolSU\Support\Connection\Connection\connector(), BristolSU\Support\Module\ModuleBuilder\create(), BristolSU\Support\Testing\CreatesModuleEnvironment\createModuleEnvironment(), BristolSU\Support\Module\ModuleBuilder\getAlias(), BristolSU\Support\Module\ModuleServiceProvider\mapAdminApiRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapAdminRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapParticipantApiRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapParticipantRoutes(), BristolSU\Support\Module\ModuleServiceProvider\registerAssets(), BristolSU\Support\Module\ModuleServiceProvider\registerConfig(), BristolSU\Support\Module\ModuleServiceProvider\registerEvents(), BristolSU\Support\Module\ModuleServiceProvider\registerModule(), BristolSU\Support\Module\ModuleServiceProvider\registerPermissions(), BristolSU\Support\Module\ModuleServiceProvider\registerScheduledCommands(), registerSettings(), BristolSU\Support\Module\ModuleServiceProvider\registerTranslations(), BristolSU\Support\Module\ModuleServiceProvider\registerViews(), BristolSU\Support\Connection\RegisteredConnector\setAlias(), BristolSU\Support\Module\Module\setAlias(), BristolSU\Support\Testing\CreatesModuleEnvironment\userApiUrl(), and BristolSU\Support\Testing\CreatesModuleEnvironment\userUrl().
baseDirectory()
function\baseDirectory () abstract
Return the path to the base directory (where the composer.json file is).
Used for registering files, will often look something like DIR . '/..'
Returns
string
Referenced by BristolSU\Support\Module\ModuleServiceProvider\loadMigrations(), BristolSU\Support\Module\ModuleServiceProvider\mapAdminApiRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapAdminRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapParticipantApiRoutes(), BristolSU\Support\Module\ModuleServiceProvider\mapParticipantRoutes(), BristolSU\Support\Module\ModuleServiceProvider\registerAssets(), BristolSU\Support\Module\ModuleServiceProvider\registerConfig(), BristolSU\Support\Module\ModuleServiceProvider\registerFactories(), BristolSU\Support\Module\ModuleServiceProvider\registerTranslations(), and BristolSU\Support\Module\ModuleServiceProvider\registerViews().
registerGlobalScript()
function\registerGlobalScript (string $path)
Register a js file to be loaded on every request.
This is useful for registering custom components. If you want to register a custom component to use in a form, pass in a js file path which registers the component.
Parameters
string $path build path e.g. 'modules/module-alias/js/components.js'
Definition at line 404 of file ModuleServiceProvider.php.
registerSettings()
function\registerSettings ()
Register settings for the module
Exceptions
BindingResolutionException
Definition at line 391 of file ModuleServiceProvider.php.
References alias(), and settings().
Referenced by BristolSU\Support\Module\ModuleServiceProvider\boot().
settings()
function\settings () abstract
Return settings required by the module
Returns
Form
Referenced by BristolSU\Support\ModuleInstance\Settings\ModuleSettingsStore\get(), BristolSU\Support\Connection\Contracts\Connector\getSetting(), BristolSU\Support\ModuleInstance\Settings\ModuleSettingsStore\register(), registerSettings(), BristolSU\Support\Connection\Contracts\Connector\setSettings(), and BristolSU\Support\Module\Module\setSettings().